### ISSUE TITLE
Add Personal Access Token Support

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#14]
- [ ] Add database model for Personal Access Tokens (PATs)
 - [ ] Define REST API interface to allow user to generate/delete tokens
 - [ ] Add auth middleware to handle PAT in place of session cookie
 - [ ] Create UI view to list user's tokens
 - [ ] Create UI view to create a new token
```[tasklist]
### User Stories
- [ ] https://github.com/flowforge/flowforge/issues/42
- [ ] https://github.com/flowforge/flowforge/issues/41
- [ ] https://github.com/flowforge/flowforge/issues/2482
```

**Comment by sammachin** [comment]
Call with customer today expressed an interest in this feature.
They would see it as a reason to take an enterprise license.

**Comment by hardillb** [comment]
We shouldn't need a PAT table in the database the AcessToken table should work

**Comment by hardillb** [comment]
Tokens should have names so that a user can have multiple with different scopes and be able to tell them apart

**Comment by hardillb** [comment]
Verified on Staging
