### ISSUE TITLE
FlowFuse certified nodes

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#1891]
### Description

Epic to track certain activities and tasks around "certified nodes"

### Background
_See also  Product Strategy Handbook - https://flowforge.com/handbook/product/strategy/_

The "Node-RED Library" offers a unique added value to many Node-RED and FlowForge users. It is already possible today to easily create technical implementations out of the box for several OT and IT protocols, thanks to the community and Node-RED library.

The logical consequence of FlowForge’s journey is to also include “custom nodes” as one element of the product. Therefore, FlowForge will offer official support for certain popular nodes and in addition enable the community to offer commercial “nodes” via FlowForge. Nevertheless, an open-source core is always required and wanted. However, premium extensions and commercial support allow the community to participate in the success of FlowForge.

(...) It’s a draft, as everything in the handbook is a draft (...)

```[tasklist]
- [ ]
- [ ] https://github.com/flowforge/flowforge/issues/1897
- [ ] https://github.com/FlowFuse/flowfuse/issues/3840
```

```[tasklist]
### User Stories / Use Cases
- [ ] 
- [ ] https://github.com/flowforge/flowforge/issues/1899
- [ ] https://github.com/flowforge/flowforge/issues/1901
- [ ] https://github.com/flowforge/flowforge/issues/1902
```

```[tasklist]
### Related activities
- [ ] flowforge/flowforge/issues/217
```
### Realization path sketch
- Begin by collecting trusted nodes as described in issue #1897 and establish official support for selected third-party Node-RED nodes by FlowForge, as outlined in issue #1901. This will allow for early feedback from users and help identify areas of improvement.

- Build upon the technical foundation established in Custom Node Catalogues, issue #217. This will also enable other user stories like #1899 and others. This will provide users with greater flexibility and ensure the platform's usability in various scenarios.

- Finally, refine the picture and requirements for enabling the community to offer commercial Node-RED nodes, as described in issue #1902.
