### ISSUE TITLE
Official Support for selected Third-Party Node-RED nodes by FlowFuse

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#1901]
### Epic

1891

### Description

As a FlowForge user and customer,
I want official support for certain third-party custom Node-RED nodes, like contrib-omron-fins, OPC-UA, S7 ...
So that I can ensure the reliability, compatibility, and performance of these nodes

### Which customers would this be available to

Specific Team Tiers (EE)
Teams

### Definition of "certified nodes"

The usage of a certified node is recommended by FlowFuse.
This includes: 

- Modules have been tested and checked for any harmful elements e.g. through a Sandworm audit and njsscan. (checks are conducted weekly)
- If a security risk occurs, we will try to fix the security issue, nevertheless we reserve the right to remove any "certified node" from the list and inform our customers.
- Compatibility with FlowFuse
- Support is not guaranteed, but we help on the best effort basis.

Optional additions:

- Documentation and Use Case examples for "certified nodes"

### List of modules
https://docs.google.com/spreadsheets/d/1gMXwR-30guVxmzSxfORq1TEW5RuZfH3JcDnb_LAibL0/edit#gid=0

```[tasklist]
### Tasks
- [ ] https://github.com/FlowFuse/flowfuse/issues/2951
- [ ] https://github.com/FlowFuse/flowfuse/issues/2971
- [ ] https://github.com/FlowFuse/website/issues/1257
```

**Comment by hardillb** [comment]
Just to clarify this is FlowForge offering consulting/support to people writing their own nodes?

**Comment by MarianRaphael** [comment]
@hardillb No, it is more about support for existing 3rd-party nodes, like e.g., contrib-omron-fins. I will clarify this and edit.

**Comment by MarianRaphael** [comment]
List of selected modules: https://docs.google.com/spreadsheets/d/1gMXwR-30guVxmzSxfORq1TEW5RuZfH3JcDnb_LAibL0/edit#gid=0

**Comment by knolleary** [comment]
@MarianRaphael we need a name for the catalogue - this is how it will appear in the Node-RED palette manager.

Do we want to go straight to `FlowFuse Certified Nodes` for the first iteration?

**Comment by MarianRaphael** [comment]
Yes
