### ISSUE TITLE
Improvements for "Multiple FlowForge Hosted Instances per Application"

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#1972]
### Description

Open Follow-up tasks for https://github.com/flowforge/flowforge/issues/1689 

(Origin https://github.com/orgs/flowforge/projects/13/views/1)

```[tasklist]
### Tasks
- [ ] https://github.com/flowforge/flowforge/issues/1969
- [ ] https://github.com/flowforge/flowforge/issues/1935
- [x] Instances name in devices table should be a link
- [ ] https://github.com/flowforge/flowforge/issues/1973
- [ ] https://github.com/flowforge/flowforge/issues/1995
```

```[tasklist]
### Ideas / Icebox
- [ ] https://github.com/flowforge/flowforge/issues/1987
- [ ] https://github.com/flowforge/flowforge/issues/1986
- [ ] https://github.com/flowforge/flowforge/issues/1985
- [ ] https://github.com/flowforge/flowforge/issues/1984
- [ ] https://github.com/flowforge/flowforge/issues/1983
- [ ] https://github.com/flowforge/flowforge/issues/1982
- [ ] https://github.com/flowforge/flowforge/issues/1981
- [ ] https://github.com/flowforge/flowforge/issues/1978
- [x] Application Overview: Instance last deployed state is blank after first creating an application
```

**Comment by joepavitt** [comment]
Small UX items here don't warrant keeping this epic open - closing
