### ISSUE TITLE
Custom Node Catalogues

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#217]
### Description

By default, Node-RED uses the community node catalogue from https://flows.nodered.org.

An admin may want to provide a custom catalog to their users. This could be in addition to, or instead of, the community catalogue.

Use cases:

 - Provide a curate/restricted list of modules from the community catalogue
 - Provide a catalogue tied to a private npm repository that are not available in the public npm repo

Some questions on the scope of this feature:

 - UI for admin to manage the catalogue contents.
 - Should we offer hosting of the private npm repo as an add-on (not a small task to make secure and scalable)?
 - If private repo (hosted or otherwise), do we provide tooling to automatically index and generate the catalog?

```[tasklist]
### Tasks
- [ ] https://github.com/flowforge/flowforge/issues/2526
- [ ] https://github.com/flowforge/flowforge/issues/2527
- [ ] https://github.com/flowforge/flowforge/issues/2759
- [ ] https://github.com/FlowFuse/flowfuse/issues/2951
```

**Comment by knolleary** [comment]
I have raised https://github.com/node-red/node-red/issues/4057 as an upstream issue to address some of the UX issues around multiple catalogs.

**Comment by joepavitt** [comment]
Looking at two tiers of catalogues:
- **Platform-level Catalog** - Vetted by FlowForge for FlowForge Cloud
- **Team Level Catalog** - Custom catalog on a team-by-team basis

**Comment by joepavitt** [comment]
> I have raised [node-red/node-red#4057](https://github.com/node-red/node-red/issues/4057) as an upstream issue to address some of the UX issues around multiple catalogs.

Would this need to be addressed before we could move forward with anything in FF?

**Comment by MarianRaphael** [comment]
Customer request: https://github.com/flowforge/flowforge/issues/1890

**Comment by joepavitt** [comment]
Also requested by @biancode - noted they have built their own implementation of this in [Portainer](https://www.portainer.io/) and using an .npmrc file

**Comment by biancode** [comment]
> Also requested by @biancode - noted they have built their own implementation of this in [Portainer](https://www.portainer.io/) and using an .npmrc file

That was the best way to use a private registry like [Cloudsmith](https://cloudsmith.com/), but we had to build our own Docker Image on-top of the flowforge/node-red Image to bring in the API-Token. Injecting Env-Variables to the NodeJS level of the Docker Container was the task to solve here, too.
