### ISSUE TITLE
Device Management at Application level

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#2334]
### Description

Currently, devices are paired with an instance. The idea here is that a device is no longer assigned to an instance, but rather to an application.

## User Story

As a FlowForge user who primarily works with Devices,
I want the capability to assign my Devices directly to an Application,
So that I can better manage and utilize my resources without the need for unnecessary instance creation.

```[tasklist]
### Management at Application level
- [ ] https://github.com/flowforge/flowforge/issues/1986
- [ ] https://github.com/flowforge/flowforge/issues/2335
- [ ] https://github.com/flowforge/flowforge/issues/2408
- [ ] https://github.com/flowforge/flowforge/issues/2609
- [ ] https://github.com/flowforge/flowforge/issues/2619
```
```[tasklist]
### Device Groups
- [ ] https://github.com/flowforge/flowforge/issues/1509
- [ ] https://github.com/flowforge/flowforge/issues/2340
- [ ] https://github.com/flowforge/flowforge/issues/2655
- [ ] https://github.com/FlowFuse/flowfuse/issues/1694
```
```[tasklist]
### Managing a large number of Devices
- [ ] https://github.com/flowforge/flowforge/issues/2381
- [ ] https://github.com/flowforge/flowforge/issues/2380
- [ ] https://github.com/flowforge/flowforge/issues/2379
```

```[tasklist]
### Pipelines
- [ ] https://github.com/flowforge/flowforge/issues/2756
```

**Comment by joepavitt** [comment]
Discussed with @MarianRaphael - explore older idea that "Instances" is a single concept, some are local to FF, some are remote (what we now call Devices). Management all consistently at the Application level - what does that UX look like?

**Comment by joepavitt** [comment]
Relevant update for this also shared here: https://github.com/flowforge/flowforge/issues/2484#issuecomment-1706456795

**Comment by robmarcer** [comment]
This has been requested by - https://app-eu1.hubspot.com/contacts/26586079/record/0-1/1956

**Comment by joepavitt** [comment]
Any specific pieces here @robmarcer? This Epic, and the tasks listed are _mostly_ implemented already. You can manage devices at the application-level, without the need for Instances

**Comment by robmarcer** [comment]
I was just checking all issues which are tagged as 'customer request' had a link to the relevant people. As far as I know we have now implemented everything the linked customer needed and we did so several weeks, possibly months ago but I didn't want to miss anything. I suggest I untag it as the customer is happy with what was delivered, OK?

**Comment by joepavitt** [comment]
> I suggest I untag it as the customer is happy with what was delivered, OK?

Tagging the relevant stories, scoped to what they asked for is the better, longer-term play, rather than the high-level epic. Okay to keep the tag on here though

**Comment by joepavitt** [comment]
Most of this is done, and doesn't warrant staying open as an Epic now. Some of the smaller UX improvements have their own standalone issues raised.
