### ISSUE TITLE
Streamlining "Time to NR-Editor"

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#2476]
### Description

Minimize the "time to value" for our customers, focusing on reducing the time from account registration to the opening of the Node-RED Editor. This Epic, entitled "Streamlining Time to Value", aims to simplify and accelerate our onboarding process. Our goal is to automate the creation of a Node-RED instance during the registration process and provide clear, intuitive guidance throughout. By removing unnecessary steps and decision-making points, we aim to enhance user experience and increase the likelihood of customer retention. 
```[tasklist]
### Tasks
- [ ] https://github.com/flowforge/flowforge/issues/2475
- [ ] https://github.com/flowforge/flowforge/issues/2447
- [ ] https://github.com/flowforge/flowforge/issues/2446
- [ ] https://github.com/flowforge/flowforge/issues/1721
- [ ] https://github.com/flowforge/flowforge/issues/2487
```

**Comment by joepavitt** [comment]
https://www.figma.com/file/JxQe6yIm6lSIYvVi1FYCtl/User-Journeys---Calls-to-Action-(FF-Cloud)?type=whiteboard&node-id=0%3A1&t=t2T4D8j2yTK7ZWzT-1

This shows our current Discovery & Action phases for onboarding

**Comment by joepavitt** [comment]
and then, from PostHog, current time distribution from registration to "Open Editor": https://eu.posthog.com/insights/iTHonoPL 

<img width="1420" alt="Screenshot 2023-07-13 at 09 30 40" src="https://github.com/flowforge/flowforge/assets/99246719/b4c9ab18-9fce-4264-bc45-0d13dd4fc473">
<img width="1433" alt="Screenshot 2023-07-13 at 09 30 44" src="https://github.com/flowforge/flowforge/assets/99246719/292bbfab-ff6a-42e4-b3f0-f93302bfeb71">

**Comment by joepavitt** [comment]
Just had a look at why users weren't converting from registered to "Open Editor" too, and found this example (amongst a few others): https://eu.posthog.com/replay/18947bcb0fc3fb1aa0-090b53f0b9fecc-26031d51-144000-18947bcb0fd3fb1e87

Seems as though Node-RED instances aren't starting properly on FF Cloud.

**Comment by joepavitt** [comment]
Just added "Time to action" (Creating an Instance) to better track this...

<img width="1378" alt="Screenshot 2023-07-13 at 09 37 18" src="https://github.com/flowforge/flowforge/assets/99246719/9111623b-0728-40ac-9eb7-2e1a1d7473d7">
