### ISSUE TITLE
FlowFuse NPM Registry

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#2759]
### Description

Set up of a private NPM registry, possibly using Verdaccio, that is accessible exclusively by devices and instances connected to the FlowFuse cloud or by customers to whom we have provided a secure access key.

## Epics

https://github.com/flowforge/flowforge/issues/217

## Functional Requirements
- [ ] Private Access: The registry should be accessible only by instances and devices connected to the FlowFuse cloud and customers.
- [ ] Secure Sharing:
- Option A: Customers can access the registry through a securely shared access key.
- Option B: An automatic decryption process for the access key is initiated when a customer licenses FlowFuse, providing seamless access to the registry.
- [ ]  Module Vetting: Before a module is added to our registry, it must be scanned for malware and undergo a code quality check.

## Future Scope
In the future, we may also offer additional packages through this registry, such as the FF Dashboard extensions, and other value-added FF exclusive services.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate
```[tasklist]
### Tasks
- [ ] https://github.com/flowforge/flowforge/issues/1901
- [ ] https://github.com/flowforge/flowforge/issues/2809
- [ ] https://github.com/FlowFuse/CloudProject/issues/243
```

**Comment by hardillb** [comment]
@MarianRaphael I could do with some response to my questions to see if we need to make updates to the custom catalogue/npmrc changes that should ship next week.

**Comment by MarianRaphael** [comment]
> What are the packages planned to be hosted in this npm repo, only FlowForge created or 3rd party?

FlowFuse created ones and copied packages that we want to support and that are scanned

> Private registries need to be scoped when referenced from the .npmrc file so only packages with known @scope/ values can be hosted.

Yes, we can configure the scope as we prefer, for example, as @flowfuse-certified.

> Is there a second issue to track hosting a catalogue.json file to go with this?

Not yet, but I will open one.

**Comment by ZJvandeWeg** [comment]
@MarianRaphael For what tier is this feature?

**Comment by hardillb** [comment]
We may want to look at a custom auth plugin for Verdaccio

**Comment by MarianRaphael** [comment]
Would a service provider (like npmjs for private packages) be the easier option for us?

**Comment by MarianRaphael** [comment]
> @MarianRaphael For what tier is this feature, both for cloud as well as for on-prem?

Starter -> FF Cloud
Teams -> Self Hosted
All paying customers should have access

**Comment by hardillb** [comment]
Technical proposal for deploying registry https://github.com/FlowFuse/CloudProject/issues/243

This doesn't cover any of the FlowForge integration (bar a start on authentication)

Also still need clarity about the Ops for this service.

**Comment by robmarcer** [comment]
This was discussed as a requirement by this potential customer - https://app-eu1.hubspot.com/contacts/26586079/record/0-2/7993766355

They need to be able to copy relevant packages selectively to a private NPM Registry which their local node.js instances can access to install FF Device Agent, Node-RED and a predefined list of custom nodes. The idea is that the registry would be updated from time to time to add new or updated packages and their dependencies.

This is so they can run a FlowFuse instance and device agents in an air-gapped network.

**Comment by hardillb** [comment]
@robmarcer Not sure this customer request is linked to this issue,

We already provide a way to provide a custom .npmrc file which will allow them to point to a local npm repo.

```
registry=https://private.repo.example.com
```

And there are multiple products that allow you to configure which packages can be proxied/cached.

Thought it will be worth pointing out that there will be a huge number of dependencies if they want to manually verify every one...

Grab me for a chat if you need more info

**Comment by robmarcer** [comment]
Thanks @hardillb. I was adding detail of the discussion as @ZJvandeWeg tagged this as a 'customer request' relating to the linked potential customer above. I felt a little context would be useful. On reflection, I've got into the 'how'. I think the potential customer is totally open to any suitable solution.
