### ISSUE TITLE
Blueprints

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#2814]
### Description

To further extend the capabilities of our Node-RED based offering and make it more accessible for our users, we will develop a set of predefined templates specifically designed for the manufacturing domain. These templates will cover key aspects like OEE Dashboards, 5S Checklists, and other commonly-used functionalities, reducing the setup time for FlowFuse users.

```[tasklist]
### Tasks
- [ ] https://github.com/flowforge/flowforge/issues/2828
- [x] MVP of #2828 - shipping in 1.12.4
```

```[tasklist]
### Templates
- [ ] OEE
- [x] Andon Dashbaord
- [ ] Work Order Status
- [ ] Process Quality Monitoring
```
```[tasklist]
### Website
- [ ] https://github.com/FlowFuse/website/issues/1256
```

**Comment by joepavitt** [comment]
Closing as we are not using this to track which Blueprints are being published
