### ISSUE TITLE
Blueprint Library

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#2828]
### Description

The Template Library is a concept analogous to the FlowFuse Team Library. It allows a FlowFuse Admin to share flow.json files with all teams. This would be a unidirectional channel, as users of teams do not have the ability to upload any flows (for that purpose, they can use the Team Library). As a result, the FlowFuse Admin can share a set of standard flows and examples with all FlowFuse teams.

```[tasklist]
### MVP - shipped in 1.12.4
- [ ] https://github.com/FlowFuse/flowfuse/issues/2871
- [ ] https://github.com/FlowFuse/flowfuse/issues/2873
- [ ] https://github.com/FlowFuse/flowfuse/issues/2874
- [ ] https://github.com/FlowFuse/flowfuse/issues/2872
```

```[tasklist]
### UX Improvements
- [ ] https://github.com/FlowFuse/flowfuse/issues/2948
- [ ] https://github.com/FlowFuse/flowfuse/issues/2945
- [ ] https://github.com/FlowFuse/flowfuse/issues/3266
- [ ] https://github.com/FlowFuse/flowfuse/issues/3265
- [ ] https://github.com/FlowFuse/flowfuse/issues/3598
```

```[tasklist]
### Future: Enable Shared Library in Node-RED
- [ ] Create Node-RED Shared Library endpoint for FlowTemplates
- [ ] Add NR Shared Library config to NR Launcher
- [ ] Add NR Shared Library config to Device Agent
```

## Epic

https://github.com/flowforge/flowforge/issues/2814

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by MarianRaphael** [comment]
Usage of existing templates instead of "Team Library" concept

**Comment by joepavitt** [comment]
Complexity of templates living at the Library level is that some of the them will have third-party nodes, loading those flows via the Library, would mean Users then have to _know_ (and search/install) the third-party dependencies

**Comment by joepavitt** [comment]
When first hearing this idea, my thought was this would be a step in the "New Instance" workflow, you choose from a set of Flow Templates (which would be broken into sections, e.g. "Blank", "Getting Started with Node-RED", "Manufacturing"

**Comment by joepavitt** [comment]
Extra extension of this work could utilise https://github.com/flowforge/flowforge/issues/2829 to allow users to "Preview" flows _before_ committing to choosing one. Improves on-ramping of new NR users, and enables exploration of NR concepts, without hte need to spin up a whole instance first.

**Comment by joepavitt** [comment]
Concern I have if we're targeting _new_ Node-RED users is how overwhelming and lost users may get/feel when first opening NR if it's already full of flows. 

They won't know where to click, or what to do. 

Ideally, we would _also_ have some tutorial/guidance/click-through for the flows too. I think I recall @Steve-Mcl saying these can be configurable.

**Comment by joepavitt** [comment]
Quick dump of some variations, some with "preview" buttons, explicit "select" in the tile, category lists on the ight, images, not fixed on any of these, just wanted to share ideas.

**Variant 1:**
<img width="1579" alt="Screenshot 2023-09-26 at 12 19 27" src="https://github.com/flowforge/flowforge/assets/99246719/fb48796a-e9ce-4313-a09f-c84db9b29786">

**Variant 2:**
<img width="1673" alt="Screenshot 2023-09-26 at 12 18 28" src="https://github.com/flowforge/flowforge/assets/99246719/df9e9e5c-09fe-43ce-8061-11cc5d408992">


**Variant 3:**
<img width="1163" alt="Screenshot 2023-09-26 at 12 17 24" src="https://github.com/flowforge/flowforge/assets/99246719/fbd868d8-026e-4247-9f75-8448253bfd9c">

**Comment by ZJvandeWeg** [comment]
I like variation 3 best, as it has larger icons for each template.

**Comment by joepavitt** [comment]
@knolleary just thinking out loud so that I've logged this:

- Name
- Description
- Flow (`json`)
- Category
- Image (for tile)

Not MVP:
- Tutorial/Guides
    - Not sure how these are generated/formatted?
- Access to Team Tiers

**Comment by joepavitt** [comment]
Other complexity for building this UI is the categories themselves, they have iconography, where does that get defined?

**Comment by joepavitt** [comment]
My other thinking would be that (similar to Audit Logs) we could have a set of pre-defined category icons, where if a category name matches, it uses that icon (we can pre-fill this with FF categories to start with)

**Comment by knolleary** [comment]
I have added two task lists the issue description that outlines the technical steps needed - splitting out MVP from future work. I'll convert the initial ones to issues where I'll put more technical design work.

**Comment by knolleary** [comment]
@joepavitt I think having a pre-canned set of categories would be a sensible quick win for the short term.

**Comment by knolleary** [comment]
With the API in place, I've added a couple `curl` examples for driving it [here](https://github.com/FlowFuse/flowfuse/issues/2871#issuecomment-1755829289)

**Comment by knolleary** [comment]
We have shipped MVP phase in 1.12.4.

I have updated the next phase task list to address the UX limitations of the MVP - with corresponding issues already raised.

**Comment by joepavitt** [comment]
This Epic can now be closed off, the majority of issues are resolved. Future ideas are already being tracked by independent issues.
