### ISSUE TITLE
Fix licensing of custom catalog feature

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#2950]
### Description

When #2526 was implemented it did not get scoped to the right license level. We need to ensure the custom npmrc and catalog list is only available to:
 - EE licensed instances
 - FF Cloud - Team tier or higher

```[tasklist]
### Tasks
- [ ] Add filter to these settings in the runtime if not EE licensed
- [ ] Add 'customCatalogs' feature flag to platform - based on EE license
- [ ] Add 'customCatalogs' feature flag to TeamType object
- [ ] In Template view, hide the relevant fields if feature flag is not set for either platform or current TeamType.
``` 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by ZJvandeWeg** [comment]
@knolleary @MarianRaphael 

> EE licensed instances

What does that mean, both Team and Enterprise? So is there parity for cloud vs self managed?

**Comment by knolleary** [comment]
> What does that mean, both Team and Enterprise?

Yes. There is parity between cloud and self-managed.

"EE licensed" was force of habit on my part to simply mean running with a license, without distinguishing which tier of license.
