### ISSUE TITLE
Implementing Device Groups Management

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#2997]
### User Story
As a FlowForge user, who manages a large number of devices,
I want to have the ability to create "Device Groups",
So that I can manage and organize my devices more efficiently by grouping and identifying them through common characteristics.

Follow-up story:
https://github.com/FlowFuse/flowfuse/issues/2989

### Scope

- Users can create a new "Device Groups" by providing a unique name 
- Users can view a list of all created "Device Groupss" with their names
- Devices can only be assigned to one Device Group at any time.
- Groups (Tag) are managed at the application level, but viewable/configurable in the pipeline
- Users can view or remove the "Device Group" for a device

### Design
https://github.com/FlowFuse/flowfuse/issues/3103

## License 
~~Teams Tier~~
Enterprise Tier

```[tasklist]
### Tasks
- [ ] https://github.com/FlowFuse/flowfuse/issues/3103
```

```[tasklist]
### Follow-ups
- [ ] https://github.com/FlowFuse/flowfuse/issues/3204
```

**Comment by MarianRaphael** [comment]
Follow-up: https://github.com/FlowFuse/flowfuse/issues/2989

**Comment by MarianRaphael** [comment]
Designs in: https://github.com/FlowFuse/flowfuse/issues/3103

**Comment by Steve-Mcl** [comment]
@MarianRaphael et al, FYI,

After resurrecting the device tagging branch and working through it with the finalised direction of Device Groups (as discussed in the 2 previous meetings and the update to this OP) I have proposed a new, simplified DB schema for introducing Device Groups.  IMO, device groups were moving a sufficient distance away from the mechanics of tagging (of being able to set a devices properties/env vars etc) into its own entity. 

I proposed this to Nick and we are in agreement: "simplifying Device Groups to a standalone, one-to many table joined to the device" (see attached schema)

I feel I can deliver this a lot quicker and believe this will not interfere with the (later) concept of tagging for settings / env vars / logical grouping etc.

![image](https://github.com/FlowFuse/flowfuse/assets/44235289/4d4f51e4-1be6-434b-8482-d5a60e995c80)

**Comment by MarianRaphael** [comment]
Device Groups should be a "Teams Tier"(ee) feature

**Comment by Steve-Mcl** [comment]
@MarianRaphael 

Audit log entries for Device Groups was not in the scope of this work but I _assume_ we/customers will want this?

If yes, can we add / schedule this work?

Thanks.

**Comment by MarianRaphael** [comment]
Right, this does not fall within the scope of this issue.
This would be the first step in that direction: [FlowFuse/device-agent/issues/188](https://github.com/FlowFuse/device-agent/issues/188).
I will open a follow-up issue specifically for Device Group Audit log entries.

**Comment by MarianRaphael** [comment]
Edit: @Steve-Mcl Please change the Tier to Enterprise

**Comment by Steve-Mcl** [comment]
> Edit: @Steve-Mcl Please change the Tier to Enterprise

Done - [fdefa11](https://github.com/FlowFuse/flowfuse/pull/3157/commits/fdefa11c001c7c25dc27aeef9e9f19d140aa0635)

**Comment by Steve-Mcl** [comment]
> Edit: @Steve-Mcl Please change the Tier to Enterprise

Front end updated

![image](https://github.com/FlowFuse/flowfuse/assets/44235289/428e3660-8221-4527-8824-fd3bc579074b)

**Comment by knolleary** [comment]
@MarianRaphael can I clarify the licensing requirement here.

> change the Tier to Enterprise

Do you mean this should only be available to Enterprise licensed platforms, or Enterprise tier teams?

The current implementation is the former - so the feature will be available to all team types on FF Cloud. If this is only meant to be available to Enterprise tier teams on FF Cloud we'll need to implement that.

**Comment by MarianRaphael** [comment]
@knolleary @Steve-Mcl What I mean is the "Enterprise tier"

**Comment by Steve-Mcl** [comment]
Staging verification:


## "Steve on Staging" team
### Device Group Ops
- [x] Add Device Group
   - [x] Application Audit Log entry present
- [x] Edit Device Group Name
   - [x] Application Audit Log entry present detailing the change
- [x] Edit Device Group Description
   - [x] Application Audit Log entry present detailing the change
- [x] Delete Device Group 
   - [x] Application Audit Log entry present
- [x] Can edit a Device Group
   - [x] Edit button reveals Save and Cancel buttons and shows available devices
   - [x] Changes are volatile until saved
   - [x] Save & cancel buttons become enabled / disabled as devices are moved into/out of a group
   - [x] Cancel loses/reverts all changes (volatile)
   - [x] Save saves all changes (survives a refresh)
   - [x] Application Audit Logs entry present detailing Add count and Remove count
- [x] Can NOT add same device to another group


### Pipeline ops
- [x] Cannot Add 1st stage in pipeline with a device group
- [x] Can Add 2nd stage with a device group
   - [x] Team Audit Log entry present
- [x] Cannot add any type of stage _after_ a Device Group
- [x] Can change a last stage instance/device stage to a device group stage
- [x] Can NOT change a middle stage (e.g. stage 2 in a 3 stage pipeline) a device group stage
- [x] Can deploy to a device group
  - [x] All devices get immediate update
  - [x] Team Audit Log entry present


### Issues noted (follow up issues/tasks to be raised for each)
1. Instance info missing if suspended: PR - https://github.com/FlowFuse/flowfuse/pull/3252
1. Empty State is displayed on pipeline when first navigated to
1. Disabling Device Groups on team type leaves configured device group in a pipeline stage (still works, displays correctly etc, needs design discussion)
