### ISSUE TITLE
Enhanced Device Settings

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3172]
### Description

Currently, the only available device setting option is environment variables. While an instance has many more setting options, not every setting option can be used for devices. This epic is about extending the Device Settings to include more possibilities, such as allowing devices to be fully managed from FlowFuse.

```[tasklist]
### This includes
- [ ] Editor settings
- [x] https://github.com/FlowFuse/flowfuse/pull/5068
- [ ] Palette management
- [ ] https://github.com/FlowFuse/flowfuse/issues/2802
- [ ] https://github.com/FlowFuse/flowfuse/issues/3292
- [ ] https://github.com/FlowFuse/flowfuse/issues/3588
```

**Comment by joepavitt** [comment]
Key items here are delivered - closing
