### ISSUE TITLE
New Applications Home Screen

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3366]
## Current Design
<img width="1146" alt="Screenshot 2024-01-22 at 07 42 11" src="https://github.com/FlowFuse/flowfuse/assets/73583313/fedffc95-59b4-40bc-8fe7-6be8768d0326">

## New Design

![image](https://github.com/FlowFuse/flowfuse/assets/73583313/4ce0b11a-e447-466b-bf37-11b6462295cf)

### Which customers would this be available to

Everyone - CE/Starter/Team/Enterprise
```[tasklist]
### Design
- [ ] https://github.com/FlowFuse/flowfuse/issues/3152
```

```[tasklist]
### Implementation
- [ ] https://github.com/FlowFuse/flowfuse/issues/3384
- [ ] https://github.com/FlowFuse/flowfuse/issues/3398
```

**Comment by joepavitt** [comment]
I think it's safe to close this as complete now? The "Favourites" nice-to-have is recorded, and shouldn't hold this open? Thoughts @MarianRaphael?

**Comment by joepavitt** [comment]
Closing this, we have deployed the MVP, requests for "Favourites" from customers has not followed. We have the issue open as a standalone task should we wish to re-visit in the future
