### ISSUE TITLE
Add ability to changing pricing to teams/instances/devices

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#3413]
### Description

We manage pricing by associating each billable 'thing' with its corresponding Stripe Product and Price Ids per Team Tier.

Whenever a team does a billable action, we reference the product/price details from the associate Team Tier. This means all teams in a tier get the same pricing details.

To introduce a pricing change, we need to agree on how it should get applied with regard existing vs new teams and what changes are needed to support that.

On the Stripe side of things, we create a new Price Object for each Product - we cannot change the $-price of an existing Price object. That will give us a new `price_id`.

If we updated the Team Tier billing details with the new `price_id`, the change would only apply the next time a Team creates/deletes a billable object (instance or device) - as that's the only time we update their subscription to match their true usage. If a team didn't make any billable changes, their subscription would remain untouched on the old price.

Whilst I need to verify this precise behaviour, the basic point is: our existing model was not required to support different teams having different pricing - so any changes in pricing will get applied to all teams in a tier as soon as that team does a billable action.

It has been proposed that any pricing change should only apply to new teams from the point in time the change is applied.

To achieve this we would need to start storing the billing information against the team itself. The Team Tier would store the 'current' product/price ids (and the $-amount we show the user), and when a Team is created, they get copied into the Team. We would then be able to modify the Team Tier's product/prices and they would only apply to new teams.

As a future iteration, I can see we would need the ability to administratively update a Team's billing info to migrate them to the new pricing at some point. Whether that is provided on a per-team basis, or some bulk-update tools/db queries, is up for discussion once we have the core requirement settled.

If this direction is agreed, the tasks are roughly:

```[tasklist]
### Tasks
- [ ] Validate existing behaviour when a price_id is changed for a product
- [ ] Add place in db to store billing info against individual teams
- [ ] Create db migration to copy billing info from TeamTier into Teams for existing teams
- [ ] On Team Create, copy over billing info into Team
- [ ] Update billing logic to pull billing info from Team, not Team Tier
- [ ] Update UI to use pricing info of the Team, not Team Tier when presenting `$` amounts 
``` 

### Which customers would this be available to

None

**Comment by ZJvandeWeg** [comment]
I think in practise we might be saved by manual billing mode in this case. 

>>>
If we updated the Team Tier billing details with the new price_id, the change would only apply the next time a Team creates/deletes a billable object (instance or device) - as that's the only time we update their subscription to match their true usage. If a team didn't make any billable changes, their subscription would remain untouched on the old price.
>>>

This is something we can script around or use the stripe CLI to trigger.

Trying to cut corners mostly as we're not changing prices that frequently, and spending too much engineering time on it would be a shame. If there's a script or set of instructions for a REPL, it might be easier to execute.

**Comment by knolleary** [comment]
/cc @MarianRaphael 

I've tested our actual behaviour around modifying the `price_ID` of devices and instances and it is slightly different to what I described above.

### Devices

1. If a team already has devices (or has ever had devices), then when devices are added/removed they will be charged at the *old* price. They are essentially locked into the price_id that was set when they created their first device.
2. If a team has never had any devices, when they add a device they will be charged at the *new* price.

To migrate an existing team to the new price_id will require some work by us to move them over.


### Instances

The logic for instances is different:

1. If a team already has a *running* instance of a given type, they will continue to be billed at the *old* price when they add/remove instances of that type.
2. When a team goes from zero->one running instances of a given type, it will be billed at the *new* price.

This will mean, for example, a team with one running instance at the old price will be updated to the new price if they suspend/resume it.
