### ISSUE TITLE
Pricing and Tier changes

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3475]
### Description

This Epic is a collection of tasks discussed here:
https://docs.google.com/document/d/1gHWvy0CKMXPCuuB5X97ZeipwO-QMFx-e3k5mtv3xi18/edit?usp=sharing

### Which customers would this be available to

Everyone - CE/Starter/Team/Enterprise
```[tasklist]
### Requirements
- [ ] https://github.com/FlowFuse/flowfuse/issues/3477
- [ ] https://github.com/FlowFuse/flowfuse/issues/3533
- [ ] https://github.com/FlowFuse/flowfuse/issues/3534
- [ ] https://github.com/FlowFuse/driver-k8s/issues/141
```

```[tasklist]
### Changes - Step 1
- [ ] https://github.com/FlowFuse/admin/issues/275
```

```[tasklist]
### Changes - Step 2
- [ ] Teams and Enterprise Tier with a minimum amount of Instances (Package)
- [ ] https://github.com/FlowFuse/CloudProject/issues/373
- [ ] https://github.com/FlowFuse/CloudProject/issues/360
```

```[tasklist]
### Other Considerations
- [ ] Implement Add-Ons
- [ ] https://github.com/FlowFuse/flowfuse/issues/3561
- [ ] https://github.com/FlowFuse/flowfuse/issues/3545
- [ ] https://github.com/FlowFuse/flowfuse/issues/3609
```

**Comment by ZJvandeWeg** [comment]
@MarianRaphael It would be great if you could add the "Bind instance size to tier" to this list

**Comment by joepavitt** [comment]
This Epic is now actioned based on the initial list - we have the "Billing" area in the Product Planning to capture any future changes
