### ISSUE TITLE
Node-RED Version Control

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#3574]
### Description

An area we need to improve, which should be a staple "wow"/highlight feature of FlowFuse is Node-RED Version Control. 

## Current Implementation

- We currently offer "[Snapshots](https://flowfuse.com/docs/user/snapshots/)" as a way of capturing point-in-time flows and associated settings, environment variables, etc.
- We also offer the ability to "rollback" to any historical snapshot taken

## Areas For Improvement

- We have had multiple customers requesting git integration within FlowFuse
- We should offer a clear picture on the history of changes made to a Node-RED Instance in FlowFuse
- We should offer a clear "differences" view between two point in time instances of a flow

## Other Information
- [Node-RED Projects](https://nodered.org/docs/user-guide/projects/)

### Which customers would this be available to

Other - Open for discussion

Requested by:

- https://app-eu1.hubspot.com/contacts/26586079/record/0-1/26674158
- https://app-eu1.hubspot.com/contacts/26586079/record/0-1/28273751

```[tasklist]
### Stories
- [ ] https://github.com/FlowFuse/flowfuse/issues/3623
- [ ] https://github.com/FlowFuse/flowfuse/issues/3624
- [ ] https://github.com/FlowFuse/flowfuse/issues/3625
- [ ] https://github.com/FlowFuse/flowfuse/issues/4305
- [ ] https://github.com/FlowFuse/flowfuse/issues/4304
- [ ] https://github.com/FlowFuse/flowfuse/issues/3666
- [ ] https://github.com/FlowFuse/flowfuse/issues/3841
```

**Comment by joepavitt** [comment]
Capturing this as a high-level epic after some discussions with customers, and internal conversations in Product review meetings.

**Comment by joepavitt** [comment]
Another example [here from Slack](https://node-red.slack.com/archives/C02V3BN77GU/p1710474864525009) whereby a team is manually copying an instance in order to make changes, then manually merging them into production instance.

**Comment by MarianRaphael** [comment]
See also https://github.com/FlowFuse/flowfuse/issues/2089

**Comment by joepavitt** [comment]
Closing as replaced by the "Area" field for the Product Planning board, this was just an admin catch-all for "Version Control" stuff
