### ISSUE TITLE
FF Dedicated Instances - Dry Runs

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#3582]
### Description

We need to do a round of dry-runs for FlowFuse dedicated instances on AWS, GCP and Azure (any others?).

This should be driven, strictly, by our documentation to ensure self-hosted users can follow the steps and successfully deploy an instance of FlowFuse in their own environment, but also has the secondary benefit that in doing these dry-runs, we can also ensure FF Dedicated instances can be spun up without hiccups.

I'm not sure what scope we need to define for each setup, but capturing this high-level item to ensure the overall piece of work is captured.

### Outcomes:

- [ ] Successfully deployed instance of FlowFuse running on AWS
- [ ] Refined and improved documentation for how to deploy FF to AWS
- [ ] Successfully deployed instance of FlowFuse running on Azure
- [ ] Refined and improved documentation for how to deploy FF to Azure
- [ ] Successfully deployed instance of FlowFuse running on GCP
- [ ] Refined and improved documentation for how to deploy FF to GCP

### Which customers would this be available to

None

**Comment by ppawlowski** [comment]
IMO points regarding AWS have been recently [taken care of](https://github.com/FlowFuse/CloudProject/issues/361) and confirmed by the [3rd party](https://github.com/FlowFuse/helm/issues/330#issuecomment-1994986204).

**Comment by joepavitt** [comment]
> IMO points regarding AWS have been recently [taken care of](https://github.com/FlowFuse/CloudProject/issues/361) and confirmed by the [3rd party](https://github.com/FlowFuse/helm/issues/330#issuecomment-1994986204).

If that's the case, then what is the value of https://github.com/FlowFuse/flowfuse/issues/3539?

**Comment by ppawlowski** [comment]
With current documentation we encourrage for clickops approach for setting up the infratructure which is error-prone way. Implementing CloudFormation template is a move ahead of devops approach of setting insfrastructure with all of its benefits. Faster and more reliable way of setting up an enfironment will be the most important one in this particular case.

**Comment by MarianRaphael** [comment]
I have added AWS as priority A; the offering will initially not include GCP and Azure. As you outlined, we are already prepared for the offering today. Nevertheless, CloudFormation scripts will streamline the process, and a dry run before going live would be beneficial.
