### ISSUE TITLE
Visualize Flows without opening a full Node-RED Editor

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3623]
### Epic

https://github.com/FlowFuse/flowfuse/issues/3574

### Description

As a FlowFuse User and Node-RED Developer,

I want to preview my flows in multiple places across FlowFuse (e.g. Blueprints, Team Library, Snapshots)

So that I can inspect the flows themselves ahead of making any respective decisions involving them.

### Which customers would this be available to

Everyone - CE/Starter/Team/Enterprise

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate
```[tasklist]
### Tasks
- [ ] https://github.com/FlowFuse/node-red/issues/8
- [ ] https://github.com/FlowFuse/flowfuse/issues/3768
- [ ] https://github.com/FlowFuse/flowfuse/issues/3798
- [ ] https://github.com/FlowFuse/flowfuse/issues/3803
- [ ] https://github.com/FlowFuse/flowfuse/issues/3838
```

**Comment by MarianRaphael** [comment]
Design in: https://github.com/FlowFuse/flowfuse/issues/3768

**Comment by joepavitt** [comment]
All tasks here are now completed - closing
