### ISSUE TITLE
Scalability: move ephemeral state to redis

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#3642]
Part of #2782 

Whilst the work under #2782 has removed most in-memory state handling, there are some pieces that are not suitable for managing via the postgres database.

 - API Rate-limiting - state is currently held in memory. The module we use supports connecting to redis out of the box (or a redis-api compatible alternative)
 - Instance/Device inflight state - when an instance/device is transitioning between states, we store some state in memory and some in the database. Need to review what, if anything, would be more suited to holding separately.

### Tasks - Phase One
- [x] Identify what ephemeral state we still have
- [x] Create 'cache' component in forge app to centralise via API
- [x] Update forge code to use cache component in place of local in-memory state

### Tasks - Phase two
- [x] Identify what technology to use (redis, or an alternative given recent licensing changes)
- [x] Add to our helm charts
- [ ] Setup authentication mechanism
- [ ] Update rate-limiting to use redis if configured
- [ ] Review instance/device lifecycle to see if any other state needs moving in

**Comment by hardillb** [comment]
Or some suitable fork/alternative (though current new license only impacts SaaS offerings of Redis iirc) e.g.

- dragonflydb
- keydb
- memcache

**Comment by hardillb** [comment]
First quick pass on existing code

### Forge App
- `forge/settings/index.js` Platform settings are loaded at startup and only updated if the instance changes them. They are never re-read from the db, the object could be shared or reads could pull from the database.
- `forge/db/controllers/Projects.js` includes inflightProjectState (object), latestProjectState (object), inflightDeploys (Set)
- ~~`forge/comms/devices.js` keeps a list of inflight commands, and device logs websocket clients, would need to ensure that session affinity is used here and heartbeats are in shared cache~~


### Drivers
- driver-localfs is not intended to be used with multiple instances (keeps used ports and file handles for logs in memory)
- driver-docker not intended to be used with multiple instances, does keep an internal in memory list of project states (this._projects) used to shortcut methods for suspened instances
- driver-k8s has the same internal project state cache (this._projects), mainly used to shortcut methods to return instantly if not found. would need to move to shared cache

I need to dig a little harder to make sure I've not missed any.

@cstns is all the ephemeral state you added recently just in the Projects controller?

**Comment by cstns** [comment]
Yes, implemented similarly to `inflightProjectState`. It should be safe to move to a cache store

**Comment by hardillb** [comment]
I'm looking at the `forge/settings` usecase

Rather than use a shared in memory cache, what about using the MQTT broker to publish settings updates to other instances. I think it's fair to say that for multi-replica forge app that a MQTT broker must be available.

**Comment by hardillb** [comment]
`forge/db/controllers/Projects.js`and `forge/comms/devices.js` done in #6115

Still need to do drivers and look at breaking out `forge/settings/index.js` to sepereate issue to do MQTT signalling

**Comment by hardillb** [comment]
I think all the parts for this are now queued up.

I think the MQTT prompting to refresh settings needs to be merged first (#6126)
Then the #6115 and after that the driver updates.

And finally the helm chart (FlowFuse/helm#700)

**Comment by hardillb** [comment]
Closing this as complete as now deployed. We can open new issues for anything discovered going forward
