### ISSUE TITLE
Migrate credentialSecret into Snapshot model

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#3644]
Part of #3622 

Task is to add credentialSecret to the ProjectSnapshots table so we are not reliant on the originating instance/device existing in order to access the snapshot.

The open question is whether the db migration should populate this column for all existing snapshots. We *could* choose to only populate for new snapshots; the logic to retrieve the credentialSecret could fall back to existing behaviour if not set on the snapshot. This would mean existing snapshots are still vulnerable to being orphaned, but the risk would be diminishing as applications tend to move forwards.

Will need to evaluate the cost/risk of doing full migration.

```[tasklist]
### Tasks
- [x] Add column to ProjectSnapshots table
- [x] Update snapshot creation logic to populate credentialSecret column
- [x] Update logic that retrieves the credentialSecret to look in the new place
```
