### ISSUE TITLE
Streamlining Node-RED Development with Integrated FlowFuse features

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3646]
### Epic

https://github.com/FlowFuse/flowfuse/issues/2246

### Description

As a: Node-RED Developer and FlowFuse User

I want to: develop my Node-RED flows utilizing FlowFuse features such as Node-RED logs, Snapshots, and the restart function directly within the same user interface

So that: I can manage and enhance my development workflow without the need to switch between different browser tabs or windows, leading to a more streamlined and efficient development process.

### Which customers would this be availble to

Everyone - CE/Starter/Team/Enterprise

### Acceptance Criteria

- [ ] Easily jump back to other FlowFuse menus
- [ ] Maintain the ability to pop out the Node-RED editor into an independent browser window if needed
- [ ]  Display Node-RED Editor and Instance management features (such as logs, snapshots, and restart functions) on the same screen

### Scope

- Just for Instances, not (yet) for devices 

### Design 

![Image](https://github.com/FlowFuse/flowfuse/assets/129537638/7b94c43b-331a-4e06-a189-ab6b8661a0c8)

### Follow-up issue

- https://github.com/FlowFuse/flowfuse/issues/3647

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

```[tasklist]
### Tasks
- [ ] https://github.com/FlowFuse/flowfuse/issues/3656
- [ ] https://github.com/FlowFuse/flowfuse/issues/3658
- [ ] https://github.com/FlowFuse/flowfuse/issues/3657
- [ ] https://github.com/FlowFuse/flowfuse/issues/3760
- [ ] https://github.com/FlowFuse/flowfuse/issues/3765
```

**Comment by joepavitt** [comment]
Only thing missing on this was the "Back" button:

<img width="1677" alt="Screenshot 2024-03-28 at 13 13 57" src="https://github.com/FlowFuse/flowfuse/assets/99246719/9e469652-dc6f-4f8a-a71c-8078a16b8fc4">

**Comment by sherbastian** [comment]
Had a chat with @Yndira-E, had a look over the ui and noted the following:
- should increase the safety area for drawer open button (padding) based on the [branding guide](https://flowfuse.com/handbook/design/branding/#construction-and-correct-usage)
- there's too much space between the drawer open button and the close drawer button (on the right side)
  - we should add a middle button that closes the drawer (visible on hover, similar to NR)
  - mimic NR sidebar resize functionality on drawer hover
- make the drawer draggable area full width of drawer instead of one small draggable handle
- the full branded logo button that opens the drawer might be a little to much, as well as two carets on both sides

I'll try and adapt the current implementation based on these notes and will have a chat with @joepavitt upon his return

**Comment by joepavitt** [comment]
Let's get out first iteration and then worry about the minor UX improvements after

**Comment by joepavitt** [comment]
@cstns @knolleary can you list here what limitations we have in terms _who_ will be able to use it

**Comment by cstns** [comment]
A starting point for the CSP & other browser security concerns is https://github.com/FlowFuse/flowfuse/issues/3800

**Comment by cstns** [comment]
referencing https://github.com/FlowFuse/flowfuse/issues/3800#issuecomment-2127133360

**Comment by joepavitt** [comment]
This can now be closed as all child tasks are completed
