### ISSUE TITLE
Auto-deploy to FlowFuse Cloud on merge with main branch

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#3681]
#### Blockers:

- [x] https://github.com/FlowFuse/helm/issues/295
- [x] #3683
- [ ] https://github.com/FlowFuse/CloudProject/issues/387

#### Nice to haves:
- [x] https://github.com/FlowFuse/flowfuse/issues/3668

#### Follow Ups
- [ ] Update website build to pull from `main` and not `maintenance` branch

**Comment by joepavitt** [comment]
Am I right in saying that we can (and do) now deploy MQTT brokers with the staging environments tagged `deploy:pr`?

**Comment by joepavitt** [comment]
With #3668 now merged, what configuration/button needs to be clicked to enable this?

**Comment by ppawlowski** [comment]
A [`Required review` deployment protection rule within `FlowFuse/helm`](https://github.com/FlowFuse/helm/settings/environments/1256381980/edit) repo needs to be unchecked.

**Comment by joepavitt** [comment]
We're also going to auto-add `deploy:pr` tag to all PRs going forward - as first iteration.

Future iteration:
- Don't add label for _just_ docs changes
- Author of the PR may be a factor, i.e. only add the label automatically if a FF team member?

**Comment by hardillb** [comment]
Just a note about testing things like the dependbot PRs for SSO packages.

This will also require us to ensure that all dependbot PRs are tested on pre-staging envs.

Testing this in a pre-staging test environment will be tricky as it will require a lot of work to configure the pre-staging environment to work with e.g. Google SSO.

**Comment by joepavitt** [comment]
> Testing this in a pre-staging test environment will be tricky as it will require a lot of work to configure the pre-staging environment to work with e.g. Google SSO.

In this case Ben - what's the proposed workflow, assuming we haven open PR, what would we need to do in order to test that in a staging environment, without the auto-deploy to production being triggered?

**Comment by hardillb** [comment]
@joepavitt to be honest that's probably a @knolleary question, I've never setup the SSO stuff (and it probably requires admin access to the g-suite tools or us hositng our own test keyclock instance)

**Comment by ppawlowski** [comment]
IMO acceptance tests executed against a staging environment should catch this kind of errors.

**Comment by ppawlowski** [comment]
https://github.com/FlowFuse/CloudProject/issues/387 contains some concerns about moving forward with this.

**Comment by joepavitt** [comment]
@ppawlowski whilst the concerns are valid, I don't want this blocking the merge on main.

I would like to move forward with production builds on merge with `main`

**Comment by ppawlowski** [comment]
@joepavitt flowfuse npm package, as well as the container image used for the deployment to both environments, are built on each push to the `main` branch.

**Comment by ppawlowski** [comment]
On each merge to `main` in the [Flowfuse/flowfuse](https://github.com/FlowFuse/flowfuse/) repo, the following things happen:
1. [FlowFuse npm package](https://www.npmjs.com/package/@flowfuse/flowfuse) is built and published to the npm registry with a `nightly` tag by [this pipeline](https://github.com/FlowFuse/flowfuse/actions/workflows/publish.yml).
2. The same pipeline triggers another one, responsible for [building a container image](https://github.com/FlowFuse/helm/actions/workflows/flowforge-container.yml) 
3. Container image build pipeline uses [flowfuse npm package](https://www.npmjs.com/package/@flowfuse/flowfuse) created in step 1 (tagged as `nightly`) to build a fresh container image
4. The resulting image is used to perform deployment on both staging and production environments.

According to the git log, this approach was introduced ~7 months ago.

**Comment by joepavitt** [comment]
Thanks @ppawlowski - it's not documented anywhere in our handbook, so wasn't aware of the details. I'm happy to put them in, will add you as a reviewer

**Comment by joepavitt** [comment]
I can see the latest builds triggered by `main` here: https://www.npmjs.com/package/@flowfuse/flowfuse?activeTab=versions

I'm not then clear on what's triggering:

> The resulting image is used to perform deployment on both staging and production environments.

Those builds were an hour ago, and production still hasn't reflected those changes.

**Comment by joepavitt** [comment]
@hardillb has pointed out we still have a manual approval step as per: https://github.com/FlowFuse/helm/actions/workflows/flowforge-container.yml

**Comment by joepavitt** [comment]
This is now live - closing
