### ISSUE TITLE
Rename Snapshots

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#3818]
### Description

Split from https://github.com/FlowFuse/flowfuse/issues/3509

Want the ability to rename a Snapshot, after it has been created.

### Which customers would this be available to

None

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate
```[tasklist]
### Tasks
- [ ] https://github.com/FlowFuse/flowfuse/issues/4281
- [ ] https://github.com/FlowFuse/flowfuse/issues/4283
- [ ] https://github.com/FlowFuse/flowfuse/issues/4286
- [ ] https://github.com/FlowFuse/website/issues/2408
```

**Comment by knolleary** [comment]
All tasks complete - closing off
