### ISSUE TITLE
Clean up UI/UX when creating an instance

### ISSUE THREAD

**Issue by ZJvandeWeg** [FlowFuse/flowfuse#3884]
### Description

To increase level of UX when creating a new instance we should fix a few things:

## Better name selection

GitHub for example has better UX when typing what this thing does and is, it keeps the repository name empty at first and lets the user type:

![Screenshot 2024-05-17 at 15 42 49](https://github.com/FlowFuse/flowfuse/assets/2529595/2761a2a6-f655-4842-856e-776d1cc9f17f)

Suggestions it does make, but like so:

![Screenshot 2024-05-17 at 15 46 29](https://github.com/FlowFuse/flowfuse/assets/2529595/b5c0adb9-2df8-49bb-9abb-9436b0e5665d)

## Blueprint selection

I think the Blueprint selection should be about the last thing to select, not the first thing. The name selection should be first. Especially as the blueprint selected doesn't prefill the form fields after them.

## Hide unavailable sizes

Come to think of it, maybe an instance size should just be bound to the tier. Either way; for the time being we should hide "Small" here:

![Screenshot 2024-05-17 at 15 47 36](https://github.com/FlowFuse/flowfuse/assets/2529595/8369f7c7-f04c-4b37-8a22-678009a869d4)

## Stack

The latest stable Node-RED version is selected, which is great. I think if a user wants to deviate, it should look and feel more like changing the blueprint. 

![Screenshot 2024-05-17 at 15 49 58](https://github.com/FlowFuse/flowfuse/assets/2529595/8ec665fd-aa90-4873-b3c8-fd112fe4d02a)
![Screenshot 2024-05-17 at 15 51 35](https://github.com/FlowFuse/flowfuse/assets/2529595/cec4a374-bac2-42b3-b94f-e7e146f7306b)

### Epic/Story

https://github.com/FlowFuse/flowfuse/issues/3839

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate
```[tasklist]
### Tasks
- [ ] https://github.com/FlowFuse/flowfuse/issues/3894
- [ ] https://github.com/FlowFuse/flowfuse/issues/3895
- [ ] https://github.com/FlowFuse/flowfuse/issues/3896
- [ ] https://github.com/FlowFuse/flowfuse/issues/3914
- [ ] https://github.com/FlowFuse/flowfuse/issues/3918
- [ ] https://github.com/FlowFuse/flowfuse/issues/3929
- [ ] https://github.com/FlowFuse/flowfuse/issues/3933
- [ ] https://github.com/FlowFuse/flowfuse/issues/3943
- [ ] https://github.com/FlowFuse/flowfuse/issues/3944
```

**Comment by ZJvandeWeg** [comment]
Hiding unavailable size was an issue for this customer @joepavitt @knolleary : https://app-eu1.hubspot.com/help-desk/26586079/view/233410279/ticket/3157950956/thread/3932457954?messageId=8bd5eb3897534f3184f8822f16e510e0

**Comment by joepavitt** [comment]
<img width="1568" alt="Screenshot 2024-05-23 at 11 34 15" src="https://github.com/FlowFuse/flowfuse/assets/99246719/bdec4cd2-9e44-430c-b650-5af6095c35fb">

Accounting for the above proposals, here's a refreshed "Create Instance" design, note also the change in header to be consistent with the others pages we've revamped more recently.

**Comment by joepavitt** [comment]
Also think the addition of a "Preview Blueprint" button here would be valuable

<img width="489" alt="Screenshot 2024-05-23 at 11 35 47" src="https://github.com/FlowFuse/flowfuse/assets/99246719/5cc45ceb-973b-4b78-820b-00a55bad81ae">

**Comment by knolleary** [comment]
I know we've been here before, but the blueprint selection *really* looks like it should be clickable along side all of those other clickable elements that have the same appearance (a rounded-corner, bordered box).

**Comment by joepavitt** [comment]
> I know we've been here before, but the blueprint selection really looks like it should be clickable along side all of those other clickable elements that have the same appearance (a rounded-corner, bordered box).

I agree, and I wasn't sure if it should default to the "Preview" option, or the "Choose another" option. I'm thinking the former, but having that as the only way to preview didn't feel obvious enough, hence adding the extra label/button below

**Comment by cstns** [comment]
Why are we replacing the entire side menu with the back button?

IMO, it adds unnecessary navigation restrictions

**Comment by cstns** [comment]
I also added a proposal task #3933 that would align the instance creation forms on the application instance form as well. 

Opinions welcomed, as the changes I proposed are breaking out of the applications page pattern

**Comment by cstns** [comment]
> I think the Blueprint selection should be about the last thing to select, not the first thing. The name selection should be first. Especially as the blueprint selected doesn't prefill the form fields after them.

I agree that the name selection should be first but the blueprint selector is complicating things at the moment in that it's embedded in the and while it's open it hides the rest of it.

I'd propose another solution in that it would extract the blueprint selection and viewing logic into a standalone dialog view which would be friendlier than hiding parts of the existing form, ux wise.

**Comment by joepavitt** [comment]
> Why are we replacing the entire side menu with the back button?

Fair feedback, happy for you to keep the existing side menu, although we do then need some "back" breadcrumb into the page header so it's easy/obvious for a user to return to the previous page.

**Comment by joepavitt** [comment]
> I'd propose another solution in that it would extract the blueprint selection and viewing logic into a standalone dialog view which would be friendlier than hiding parts of the existing form, ux wise.

My conern here would be, then when previewing a Blueprint, we have a Dialog over a Dialog?

**Comment by cstns** [comment]
I made a quick POC to showcase my ideea:

https://github.com/FlowFuse/flowfuse/assets/20094749/75de6285-1526-4d96-b392-3f9b1d8edbfa

Yes, I had to disable the blueprint tile preview for this specific case.

It still needs polishing, selection is not done yet, and other loose ends but this would not break the flow context of creating an instance when needing to select a different blueprint

**Comment by joepavitt** [comment]
I really like that, although - responsiveness? That's a nice, wide screen you've got yourself there, how does that look on a standard laptop screen?

**Comment by cstns** [comment]
That would be one point that would need polishing! currently I have the blueprint selector and flow previewer on a 40-60 division. It's responsive but does not do well on mobile or smaller devices. 

Another point would be to make the blueprint tile 'selectable' to know which one is selected at a given time.

I could go in dept with this idea and come up with proper solutions if it's accepted as a feature

**Comment by joepavitt** [comment]
can you do a quick screenshot of what it looks like on a standard laptop screen please?

**Comment by cstns** [comment]
https://github.com/FlowFuse/flowfuse/assets/20094749/a29df39c-8793-481c-94a1-68cdf1a4d4a4

14" @ 1920x1080

**Comment by cstns** [comment]
The only thing I can find inconvenient is having to click on the preview blueprint tile which opens a modal and close the modal afterwards. It adds a couple of clicks overhead.

**Comment by joepavitt** [comment]
Can you open up a new issue for the proposed blueprint dialog please? Put these recordings into the new issue, link it into the tasklist here, and I'll add some comments on the UX there

**Comment by cstns** [comment]
> Can you open up a new issue for the proposed blueprint dialog please? Put these recordings into the new issue, link it into the tasklist here, and I'll add some comments on the UX there


created https://github.com/FlowFuse/flowfuse/issues/3944

**Comment by cstns** [comment]
removed #3946 because it can be treated as a standalone item

**Comment by knolleary** [comment]
All primary tasks complete and in production. Closing this issue off.
