### ISSUE TITLE
Devices UX: Bulk delete

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#3953]
- Add bulk action/check support to the Devices browser
- Enable "delete" option for all selected devices

```[tasklist]
### Tasks
- [ ] https://github.com/FlowFuse/flowfuse/issues/4208
- [ ] https://github.com/FlowFuse/flowfuse/issues/4218
- [ ] https://github.com/FlowFuse/website/issues/2369
```

**Comment by Steve-Mcl** [comment]
All done & verified on prod. closing this issue.

![Image](https://github.com/user-attachments/assets/b967f432-b16f-4e6d-b8aa-6fe67f74a37a)
