### ISSUE TITLE
LDAP: support team membership management

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#4002]
Our SAML SSO options provide support for managing team membership and roles via SAML groups.

This was not included in our first iteration of LDAP SSO support, but we should fill that gap.

```[tasklist]
### Tasks
- [ ] Research LDAP group membership and how it would apply to FF teams
- [ ] Add team membership management options to LDAP admin dialog
- [ ] Update LDAP auth flow to include team membership management
```

 - https://app-eu1.hubspot.com/contacts/26586079/record/0-2/8175387106
 - https://app-eu1.hubspot.com/contacts/26586079/record/0-2/9822854636

**Comment by hardillb** [comment]
getting a list of groups a ldap user belongs to can be done with something like the following:

```
ldapsearch -b ou=groups,dc=hardill,dc=me,dc=uk -x '(uniqueMember=uid=hardillb,ou=users,dc=hardill,dc=me,dc=uk)'
```

or

```
const { Client } = require('ldapts')
const main = async () => {
    const opts = {
        url: 'ldap://isp-pi.loc'
    }
    const adminClient = new Client(opts)

    const filter = '(|(uniqueMember=uid=hardillb,ou=users,dc=hardill,dc=me,dc=uk)(member=uid=hardillb,ou=users,db=hardill,dc=me,dc=uk)'

    const { searchEntries } = await adminClient.search('ou=groups,dc=hardill,dc=me,dc=uk', {
        filter,
        attributes: ['cn']
    })

    // console.log(searchEntries)
    for (const i in searchEntries) {
        console.log(searchEntries[i].cn)
    }
    adminClient.unbind()
}

main()
```
