### ISSUE TITLE
Search functionality on "Applications" view

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4014]
Our "Instances" and "Devices" page include a search bar, but the "Applications" view does not. Users should be able to search for any application, instance or device on this screen to make it easier to find their relevant resources. The content below should then filter accordingly

### First Iteration:

- Search application name, filter the applications

### Future Experimentation:

- Can we do a search across all applications, instances and devices, and filter accordingly? If you match an application name, show all instances/devices inside it, otherwise just show the relevant instances/devices?
- How should we handle the fact we only show 3 instances/devices per application currently...
```[tasklist]
### Tasks
- [ ] https://github.com/FlowFuse/flowfuse/issues/4142
- [ ] https://github.com/FlowFuse/flowfuse/pull/4148
- [ ] https://github.com/FlowFuse/flowfuse/issues/4157
- [ ] https://github.com/FlowFuse/flowfuse/issues/4166
- [ ] https://github.com/FlowFuse/flowfuse/issues/4167
- [ ] https://github.com/FlowFuse/flowfuse/issues/4176
```

**Comment by joepavitt** [comment]
First Iteration:
- Search application name, filter the applications

Experimentation:
- Can we do a search across all applications, instances and devices, and filter accordingly? If you match an application name, show all instances/devices inside it, otherwise just show the relevant instances/devices?
- How should we handle the fact we only show 3 instances/devices per application currently...

**Comment by joepavitt** [comment]
Closing as most of the work here, and above MVP is done. Only open issue (low priority) has been scheduled.
