### ISSUE TITLE
Static Asset Service

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4194]
### Description

When building on FlowFuse, we now have the capability to have persistent file storage. This epic captures user stories that could be unlocked given the new, unlocked, functionality:

### Which customers would this be available to

Team + Enterprise Tiers (EE)

```[tasklist]
### Design Tasks
- [ ] https://github.com/FlowFuse/flowfuse/issues/4352
```

```[tasklist]
### User Stories
- [ ] Serving of static assets (e.g. images) to FlowFuse Dashboard
- [ ] Serving of npm libraries to FlowFuse Dashboard
- [ ] Providing access to static assets (e.g. csv files, tensor flow models) in flows running on FF
```

```[tasklist]
### Engineering Tasks
- [ ] https://github.com/FlowFuse/nr-launcher/issues/273
- [ ] https://github.com/FlowFuse/flowfuse/issues/4357
- [ ] https://github.com/FlowFuse/flowfuse/issues/4358
- [ ] https://github.com/FlowFuse/flowfuse/issues/4359
- [ ] https://github.com/FlowFuse/nr-launcher/issues/274
- [ ] Support multiple file upload
```

Listing items currently out of scope of the design. However this will lay the groundwork needed for these items:

```[tasklist]
### Out of Scope
- [ ] Versioning of files when creating snapshots
- [ ] Deploying files to devices
- [ ] Handling static assets in DevOps Pipelines
- [ ] Managing files whilst instance is suspended
```

See also:
 - https://github.com/FlowFuse/flowfuse/issues/3790

**Comment by joepavitt** [comment]
> Do we want to add some code to the nr-launcher to allow file lists, upload/delete from persistent storage?

If that's what would be required - then yes 🙂

**Comment by hardillb** [comment]
Well, it's the easiest way to get a consistent view of the available storage (especially on k8s)

**Comment by knolleary** [comment]
The core functionality here is the ability to manage the files stored in persistent storage for an instance. That requires:

 - Launcher API for basic file operations (listing, uploading, deleting, renaming)
 - Forge API to expose API to frontend
 - Frontend provide a file-browser like UI

**Comment by joepavitt** [comment]
@knolleary are we saying here that assets would be instance-bound? Or could there be scope for having them application/team bound at a later point? Thinking more of Dashboard use-cases with static images/logos

**Comment by knolleary** [comment]
>are we saying here that assets would be instance-bound?

First iteration is instance bound. Having files that are shared to all instances could be a future enhancement once we have the basics in place.

For the dashboard use case (wanting the same static assets in multiple instances), the workaround would be to add them to one instance and access them from there in the others.

**Comment by joepavitt** [comment]
Quick designs to give direction when construction the front-end. Will follow up with details on the "Upload" interaction soon

![Image](https://github.com/user-attachments/assets/7e0846bd-5ca5-43f7-92d0-3faec0e4fc34)
![Image](https://github.com/user-attachments/assets/fe651129-a62b-498f-8bc4-c35e123f3a26)

**Comment by knolleary** [comment]
I had more of a file browser ux in mind, rather than a flat list of individual files. The sharing option (whether to expose via http) would be done at the folder level (we can't do individual files)

**Comment by joepavitt** [comment]
I didnt quite follow the need to share? 

Surely anything in the assets is then available? Or is the idea that you could store stuff for future use, but not have it publicly available just yet?

**Comment by joepavitt** [comment]
> I had more of a file browser ux in mind, rather than a flat list of individual files. 

Yep, absolutely the right direction to go, I had 1 hour to flesh out a few different pages, so this was v rushed

**Comment by knolleary** [comment]
> I didnt quite follow the need to share?

For the use-case: Providing access to static assets (e.g. csv files, tensor flow models) in flows running on FF - the files need to be accessible to the flows on the local file system, but that doesn't mean I want them to be HTTP accessible.

**Comment by knolleary** [comment]
One UX issue to consider; if the instance is suspended, then nr-launcher isn't running and we don't have access to the filesystem to manage its files. That *might* be achievable by mounting the file-system elsewhere temporarily, but that gets complicated (and sure if it would be possible in the docker version). So considering that out of scope for first iteration.

**Comment by joepavitt** [comment]
> the files need to be accessible to the flows on the local file system, but that doesn't mean I want them to be HTTP accessible.

Got it, so essentially difference between accessible in Node-RED in a flow, or if they're _also_ accessible through Dashboard too?

**Comment by joepavitt** [comment]
> the files need to be accessible to the flows on the local file system, but that doesn't mean I want them to be HTTP accessible.

Got it, so essentially difference between accessible in Node-RED in a flow, or if they're _also_ accessible through Dashboard too?

**Comment by knolleary** [comment]
>  essentially difference between accessible in Node-RED in a flow, or if they're also accessible through Dashboard too?

Correct.

**Comment by hardillb** [comment]
>One UX issue to consider; if the instance is suspended, then nr-launcher isn't running and we don't have access to the filesystem to manage its files. That might be achievable by mounting the file-system elsewhere temporarily, but that gets complicated (and sure if it would be possible in the docker version). So considering that out of scope for first iteration.

Docker has the whole root "volume" mounted to do clean up, but the k8s forge app doesn't currently have any access to the volumes that are mounted into the Instances

**Comment by joepavitt** [comment]
First iteration delivered, only outstanding follow up is the "visibility"/share feature which will come in 2.9

**Comment by cstns** [comment]
Is this feature safe to close? The out of scope tasks have been moved to https://github.com/FlowFuse/flowfuse/issues/4556, not sure if we'd need to do the same for the user stories task list.
