### ISSUE TITLE
Improving the MQTT Experience with FlowFuse

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4206]
### Description

This epic is to capture thoughts and ideas on how we can, with FlowFuse, improve the experience of working with MQTT and Node-RED together.

### Which customers would this be available to

Other (See comments)
```[tasklist]
### Tasks
- [ ] Surfacing MQTT brokers that exist in a Team/Application/Instance
- [ ] Permit configuration of MQTT brokers as a centralised resource in a FlowFuse Team/Application
- [ ] Visualising MQTT topic structures for a given broker
- [ ] https://github.com/FlowFuse/flowfuse/issues/1350
```

**Comment by hardillb** [comment]
Data Point.

One of the popular "public" free access brokers (`test.mosquitto.org`) has a hard limit on the number of connections from a single IP address. The FF Cloud Ingress IP has reached that limit.

**Comment by joepavitt** [comment]
Closing off as covered by plenty of other traffic already, which have better focus on user value
