### ISSUE TITLE
Add multiple selection and bulk deletion to Device Browser

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#4218]
```[tasklist]
### Tasks
- [x] check boxes for each row
- [x] select all in header
- [x] trash button in device browser toolbar adjacent to search input (enable/disable based on selection)
- [x] e2e tests
- [x] update rbacs doc
```
