### ISSUE TITLE
Instance/Device Management Issues

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4250]
### Description

Since the move to vuex store for state management for devices & instances, w've uncovered a considerable number of broken pieces. Using this issue to keep track of those found:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate
```[tasklist]
### Tasks
- [ ] https://github.com/FlowFuse/flowfuse/issues/4249
- [ ] https://github.com/FlowFuse/flowfuse/issues/4248
- [ ] https://github.com/FlowFuse/flowfuse/issues/4246
- [ ] https://github.com/FlowFuse/flowfuse/issues/4203
```

**Comment by joepavitt** [comment]
FYI @Steve-Mcl

**Comment by joepavitt** [comment]
@Steve-Mcl I have a fix incoming which i think will cover 4 of the 4 in our list. #4203 is a separate problem though.
