### ISSUE TITLE
Bill of Materials - View Only

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4308]
Provide a view at both the Team and Application level which details all third-party Node Module dependencies. It should detail the version installed, and where those modules are distributed across the Teams applications/instances.

For this first iteration, this is a view-only mode, but users should be able to get quick access to their instances/applications from this view in order to correct dependencies if required.
```[tasklist]
### Tasks
- [ ] https://github.com/FlowFuse/flowfuse/issues/4362
- [ ] https://github.com/FlowFuse/flowfuse/issues/4363
- [ ] https://github.com/FlowFuse/flowfuse/issues/4501
- [ ] https://github.com/FlowFuse/flowfuse/issues/4534
- [ ] https://github.com/FlowFuse/flowfuse/issues/4536
- [ ] https://github.com/FlowFuse/CloudProject/issues/523
- [ ] https://github.com/FlowFuse/website/issues/2565
- [ ] https://github.com/FlowFuse/CloudProject/issues/524
```

**Comment by joepavitt** [comment]
Very rough layout idea for this:

![Application - Dependencies](https://github.com/user-attachments/assets/a8786db1-f316-468a-b062-f8998fe29f10)

**Comment by joepavitt** [comment]
I've loosely scheduled this for 2.9 @knolleary, and haven't broken it down into engineering task yet, but if we have scope, could pull this into 2.8, for at least the API development work

**Comment by cstns** [comment]
closing, first iteration task list completed
