### ISSUE TITLE
Onboarding: FlowFuse Self-Hosted

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4310]
### Description

May be some overlap with #3839

This Epic is to capture hurdles and areas for improvement for the onboarding process for FlowFuse Self-Hosted. 

### Review

As part of this exercise, we will be conducting reviews of the full installation and setup of FlowFuse in self-hosted environments.

For each scenario it is important to have a blank slate, install FlowFuse and setup FlowFuse with the relevant settings such that it is possible to run an instance of Node-RED in FlowFuse.

```[tasklist]
### Scenarios
- [ ] https://github.com/FlowFuse/flowfuse/issues/4571
- [ ] https://github.com/FlowFuse/flowfuse/issues/4573
- [ ] https://github.com/FlowFuse/flowfuse/issues/4555
```

Any friction, concerns and areas for improvement should then be documented in the following tasks lists which are broken into two sections:

### Installation

The process of retrieving a copy of FlowFuse and running in a particular environment. Ideally, this would be a single line install in some capacity. This can also cover improvements for onboarding resources like documentation/videos.

```[tasklist]
### Installation
- [ ] https://github.com/FlowFuse/flowfuse/issues/4570
- [ ] https://github.com/FlowFuse/flowfuse/issues/4574
- [ ] https://github.com/FlowFuse/flowfuse/issues/4572
- [ ] https://github.com/FlowFuse/customer/issues/249
- [ ] Remove "flowforge" mentions from our installation docs
- [ ] https://github.com/FlowFuse/flowfuse/issues/4631
- [ ] https://github.com/FlowFuse/flowfuse/issues/4632
- [ ] https://github.com/FlowFuse/flowfuse/issues/4633
- [ ] https://github.com/FlowFuse/flowfuse/issues/4634
- [ ] https://github.com/FlowFuse/flowfuse/issues/4635
- [ ] https://github.com/FlowFuse/flowfuse/issues/4636
```

### Setup & Configuration

Having an available instance of FlowFuse, this is a review/assessment of the setup steps required to then having a running instance of Node-RED.

```[tasklist]
### Setup & Configuration
- [ ] https://github.com/FlowFuse/flowfuse/issues/4638
- [ ] Idea: for quick-start purposes allow to run pre-configured app and present login page instead of setup
```

### Which customers would this be available to

Self-Hosted

**Comment by zackwasli** [comment]
Lots of issues with wildcard DNS. Larger orgs do not like the vulnerability it poses and it can take a month or more to get approval just for DNS, delaying evaluation.

Customers/prospects that had an issue:

https://app-eu1.hubspot.com/contacts/26586079/record/0-2/7845572820
https://app-eu1.hubspot.com/contacts/26586079/record/0-2/9080239048
https://app-eu1.hubspot.com/contacts/26586079/record/0-2/11792021958

**Comment by knolleary** [comment]
One pain point for both docker/k8s is the need to create the config files needed to run the platform. We should provide interactive scripts to generate the files. Have added items for both to the tasks above.

**Comment by hardillb** [comment]
We have a script from the AWS/Digtial Ocean build to build the config file for docker, we should be able to reuse that

**Comment by joepavitt** [comment]
Regarding the guided script you mentioned @hardillb - would that be guiding users through https://flowfuse.com/docs/install/docker/#configuring-flowfuse?

**Comment by hardillb** [comment]
Yes, it does the search/replace for the domain and email settings in the flowforge.yml and the docker-compose.yml files

**Comment by joepavitt** [comment]
Chatting with @ppawlowski about what questions user's are likely to have:

1. Are you installing for evaluation or for production environment?
2. Are you deploying into a Cloud environment (e.g. AWS) or dedicated hardware (e.g. factory floor)
3. If on Dedicated Hardware - What operating System?

What other considerations do they need to have when deciding with of the four paths (Docket, k8s, Do, Docker on AWS) that a user would need to know?

**Comment by ZJvandeWeg** [comment]
@joepavitt Any updates on this issue? I'd love to understand what's being done to have a bigger install base for FlowFuse

**Comment by joepavitt** [comment]
@ppawlowski as part of your exercise here, could you produce a simple checklist of _things_ that a user needs to actually setup/install, in order to have an instance of FlowFuse running? e.g. DNS Records, SMTP Server for e-mail notifications, TLS configuration

**Comment by joepavitt** [comment]
Chatting with Piotr - "Quickstart Guide" option on the `install` page, _"Docker Compose, 2/3 commands and you are done"_

**Comment by joepavitt** [comment]
<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/aa8f534a-e2ef-4c26-a434-79e076d158c6" />

Just having a call with @ppawlowski - just under 50% of traffic to "Install Self Hosted FlowFuse" then click the button "setup an alternative to DNS".

I know this has been brought up before, but it's the single biggest point of friction when setting up FF locally. Just want to make sure we have _documented_ the _why_ on this. @hardillb can you give a quick TLDR please, I know we've discussed this before, just want to document here.

**Comment by joepavitt** [comment]
Also, general update on flow here:

- 40 people to the page
- 25 people clicked the "copy" for "Step 2: Download Compose File"
- 12 clicked "copy" for "Step 3: Start the Application"
- 9 people clicked to get more info on the setup in the "guide"

**Comment by hardillb** [comment]
The DNS wildcard entry is required so that each instance can has it's own hostname (on a single shared sub domain) without having to manually set up a DNS entry for the instance at the time it is created. It basically `*.ff.example.com`  points to the IP address of the Docker host machine where `*` means anything

Each Node-RED instance requires it's own hostname (or what the browser considers to be, e.g. different port numbers for localfs) for the following reasons:

1. It provides the security boundary between instances (e.g. one instance can have basic http auth and another have FF User auth and not clash). This explicitly not for the Editor (why we can do path based proxying for the remote device editor)
2. Keeps web applications hosted in the instances sandboxed from each other.
3. The reverse proxying to expose the containers from inside docker uses the hostname to determine which container to route to

**Comment by gstout52** [comment]
The goal is for self-hosted customers to have the easiest path possible from clicking to download FlowFuse to deploying a Node-RED instance. Along with https://github.com/FlowFuse/flowfuse/issues/5950, these serve as focus areas for the next release: improving the self-hosted setup experience.

We will review the different paths a user can take and ensure that there are either technical solutions or conveniently accessible education solutions provided to the customer.

**Comment by gstout52** [comment]
@ppawlowski Please validate if the wildcard DNS requirement applies outside of Docker/Kubernetes. What about Windows?

The work for this issue will be to discover the smoothest path(s) possible to SH installation.

**Comment by ppawlowski** [comment]
> [@ppawlowski](https://github.com/ppawlowski) Please validate if the wildcard DNS requirement applies outside of Docker/Kubernetes. What about Windows?

It applies everywhere.

**Comment by hardillb** [comment]
@gstout52 The only "native" install on Windows is LocalFS and that is not a practical solution for a production deployment.

Docker on Windows comes with extra licensing costs from Docker, and while you can add Windows nodes to a Kubernetes cluster it's a specialised use case, and we do not build any Windows native containers.

In short Windows is just not a practical platform to deploy FlowFuse on (running a device agent on Windows perfectly fine, but not the full stack).

**Comment by gstout52** [comment]
@dgatti0213 I would appreciate your thoughts on this thread in light of https://github.com/FlowFuse/flowfuse/issues/6214

**Comment by hardillb** [comment]
To be crystal clear here wildcard DNS (or by granting the FlowFuse environment the ability to create it's own DNS records) is a fundamental requirement of the product.

There is no way round it

**Comment by dgatti0213** [comment]
> To be crystal clear here wildcard DNS (or by granting the FlowFuse environment the ability to create it's own DNS records) is a fundamental requirement of the product.
> 
> There is no way round it

Isn't wildcard DNS only required for creating Hosted instances of Node-Red within the Flow-Fuse platform?

**Comment by hardillb** [comment]
> Isn't wildcard DNS only required for creating Hosted instances of Node-Red within the Flow-Fuse platform?

That is the core premise of the product....

But it is also used to provide hostnames for a number of other features like MQTT broker and NPM registry.
