### ISSUE TITLE
Frontend: File Browser UX

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4358]
Design Task: https://github.com/FlowFuse/flowfuse/issues/4352

```[tasklist]
### Tasks
- [x] Develop the front-end for the Static Asset service, available in the tabs at an _Instance_ level.
- [x] Should include the addition of a `files/assets` service to interface with the new [REST API](https://github.com/FlowFuse/flowfuse/issues/4357).
- [ ] https://github.com/FlowFuse/flowfuse/issues/4419
```

**Comment by cstns** [comment]
closing, fixed by https://github.com/FlowFuse/flowfuse/pull/4398 and https://github.com/FlowFuse/flowfuse/issues/4419
