### ISSUE TITLE
Frontend for Bill of Materials

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4363]
API Issue: https://github.com/FlowFuse/flowfuse/issues/4374

Should be available for Team/Enterprise Tier
```[tasklist]
### Tasks
- [ ] https://github.com/FlowFuse/flowfuse/pull/4479
- [ ] https://github.com/FlowFuse/flowfuse/issues/4501
- [ ] https://github.com/FlowFuse/website/issues/2565
```

**Comment by joepavitt** [comment]
## Design: Draft 1

![image](https://github.com/user-attachments/assets/292aa10b-1758-4521-afbc-4d5fa12fe3b5)

**Comment by cstns** [comment]
closing, fixed in https://github.com/FlowFuse/flowfuse/pull/4479
