### ISSUE TITLE
UX: Add functionality to enable "Share"/"Visibility" feature for Static Assets

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4419]
With https://github.com/FlowFuse/flowfuse/issues/4358 we delivered the Static Assets service which allows users to upload files and create folders to organise files such as `csv`, `json`, etc.

In this task, we also want to implement the ability to expose those files on the static HTTP server, for easier serving to things like Node-RED Dashboard.

This access is managed at the folder-level - more detail available in the "Share Setting" section of https://github.com/FlowFuse/flowfuse/issues/4357
```[tasklist]
### Tasks
- [ ] https://github.com/FlowFuse/flowfuse/issues/4449
- [ ] https://github.com/FlowFuse/flowfuse/issues/4461
- [ ] https://github.com/FlowFuse/website/pull/2592
- [ ] https://github.com/FlowFuse/flowfuse/pull/4514
```
