### ISSUE TITLE
Refine MQTT offering details

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4498]
With technical feasibility established, we can now begin to shape the MQTT offering for FlowFuse. Outstanding items to consider are:

```[tasklist]
### Tasks
- [x] How will MQTT offering be priced?
- [x] How will MQTT broker(s) be exposed?
- [x] Define MQTT service limitations
- [x] Define how the service relates to the Project nodes as they currently exist and/or how they evolve
```

Following these outstanding items being addressed, sizing and delivery estimation can be established and #4433 should be consulted to refine the user experience designs before front-end development work can begin.

**Customer Insights**
Here are private notes from a call with a prospect who has asked for an MQTT service. https://docs.google.com/document/d/1ENdhMQTK0_WVtVhh47eS6aBmK0gOajAf8u4x9PGzur8/edit#heading=h.rodpwdh8kk4r

**Comment by joepavitt** [comment]
> How will MQTT broker(s) be exposed?

It is my understanding we will be going for single broker, multiple clients. So each team will be able to provision _clients_ rather than _brokers_ - is my understanding correct here @hardillb?

**Comment by hardillb** [comment]
Yes, current plan is a single shared multi-tenant broker.

Teams will be able to provision client credentials/acls that will be allowed to connect to their tenant.

**Comment by gstout52** [comment]
Regarding pricing, **I think we should offer this service to Enterprise teams only, for free, and limit them to 20 clients**. 
Above 20 clients, I recommend $2 per client.

Rationale:
- EMqX, HiveMQ, and Cedalo all offer a broker like what we are proposing, either for free (EMqX, HiveMQ) or for $51 (Cedalo).
- We are unable to charge based on usage for now, so we are only able to charge based on connected clients. It is possible that we will pay quite a lot to EMqX for traffic, and as of now we can't pass that on in the form of usage-based pricing. So, it makes sense to charge slightly more than the average price for Cedalo's lowest-priced plan.

Comparisons:
- Cedalo free is limited to 30 clients, 30GB/mo, and $0.16 per GB after 
- EMqX free is limited to 1000 connections, but 1GB/mo of traffic. (There is some behind the scenes pay-as-you-go pricing involved as well.)
- HiveMQ free is limited to 100 clients and 10GB/mo

Once this is released, we should measure data usage and add that to our pricing down the line. We should look at the volume of messages sent, the amount of data sent, and the number of clients we see customers using.

**Comment by ZJvandeWeg** [comment]
@hardillb Can we limit on the number of client? (I assume so?) And does that imply that if X clients are configured the number of concurrent connections is also limited to X?

**Comment by hardillb** [comment]
@ZJvandeWeg yes we can limit the number of clients

**Comment by ZJvandeWeg** [comment]
@hardillb Does that also limit the connections? Or are those different? I could see use cases where a set of credentials are configured and rolled out on mass? Or is that not how MQTT works?

**Comment by hardillb** [comment]
Yes, for MVP it will require 1 set of credentials per device.

MQTT credentials consist of 3 things (normally), username, password and client-id.

client-id must be unique across a broker, so to enforce limits on number of connected clients MVP will require that username = client-id.

Future developments of the broker we are using will allow per tenant client limiting that will remove this requirement.

**Comment by gstout52** [comment]
I've added a proposal for an SLA for our broker service to the meeting/pricing doc, at the very bottom of the page. https://docs.google.com/document/d/12BueZ6zpUDAgW3bFa2wVB1dgdWeOsCPh4-aL9INj9Rw/edit

@hardillb I'd be grateful if you could give it a thumbs up that the proposal fits with our discussion.

**Comment by gstout52** [comment]
@joepavitt Can we add PostHog events for MQTT usage? For example: connected a client, published to a topic, subscribed to a topic.

**Comment by knolleary** [comment]
@gstout52 no, we cannot instrument the activity of a client on the broker at that level.

**Comment by hardillb** [comment]
We could possibly add events around creating/deleting Clients

**Comment by hardillb** [comment]
I think we can tick the define service limitations for current MVP

We've started to discuss Project node integration, but I think that should be it's own issue.

**Comment by joepavitt** [comment]
> although the specific implementation details for that is not something I have to hand.

PH will pick this up automatically, no need to do anything

**Comment by joepavitt** [comment]
@gstout52 I've added an MQTT Client section to our Product Feature Tracking Dashboard: https://eu.posthog.com/project/2209/dashboard/2923?highlightInsightId=ZG26N2a9

**Comment by gstout52** [comment]
I've added a section at the bottom of the pricing doc that describes usage limitations we can publish. Please review @ZJvandeWeg , @knolleary , @hardillb . Thank you!
