### ISSUE TITLE
Static Asset Service - Phase 2

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4556]
### Description

Task list taken from [Phase 1](https://github.com/FlowFuse/flowfuse/issues/4194)

```[tasklist]
### Out of Scope
- [ ] Versioning of files when creating snapshots
- [ ] Deploying files to devices
- [ ] Handling static assets in DevOps Pipelines
- [ ] Managing files whilst instance is suspended
```

See also:
 - https://github.com/FlowFuse/flowfuse/issues/3790

### Which customers would this be available to

None
