### ISSUE TITLE
Replace the AssetCompareDialog, VisibilitySelector, ApplicationLogs ff-dropdown with the new ff-listbox component

### ISSUE THREAD

**Issue by cstns** [FlowFuse/flowfuse#4562]
```[tasklist]
### Tasks
- [x] Replace the ff-dropdown with ff-listbox in frontend/src/components/dialogs/AssetCompareDialog.vue:9
- [x] Replace the ff-dropdown with ff-listbox in frontend/src/components/file-browser/VisibilitySelector.vue:2
- [x] Replace the ff-dropdown with ff-listbox in frontend/src/pages/application/Logs.vue:10
```
