### ISSUE TITLE
Replace the InstanceLogs and AuditLogBrowser ff-dropdown with the new ff-listbox component

### ISSUE THREAD

**Issue by cstns** [FlowFuse/flowfuse#4563]
```[tasklist]
### Tasks
- [x] Replace the ff-dropdown with ff-listbox in frontend/src/pages/instance/Logs.vue:7
- [x] Replace the ff-dropdown with ff-listbox in frontend/src/components/audit-log/AuditLogBrowser.vue:12
- [x] Replace the ff-dropdown with ff-listbox in frontend/src/components/audit-log/AuditLogBrowser.vue:22
```
