### ISSUE TITLE
Add control over contents of exported and imported Snapshots

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4605]
### Description

We offer the feature to "Export" Snapshots, this contains, in a single file, the `flows`, `credentials` and `environment variables` for a given Instance. Users can then _import_ that into another Application, or instance of FlowFuse.

The challenge here is that we have customers running multiple instances of FlowFuse, where one instance is entirely development-only, and the other is production-only, and they want to be able to transfer instances between. The difficulty here is that our DevOps Pipelines are limited to instances _within_ a single FlowFuse instance, and as such, users are having to resort to manual export/import.

The manual route works, but contains env vars from development environments, and overwrites production credentials when imported. As such, the following is required of our import/export functionality:

```[tasklist]
### Tasks
- [ ] Offer users the option to toggle on/off the inclusion of "Flows", "Credentials" and "Environment Variables" when exporting a Snapshot
- [ ] Offer users the option to toggle on/off the inclusion of "Flows", "Credentials" and "Environment Variables" when importing a Snapshot
- [ ] When including Environment Variables, we should offer the following: "Include Keys & Values", "Include Keys Only"
```

We already have a similar UX for the control of the contents in the "Duplicate Instance" here:

![image](https://github.com/user-attachments/assets/6a878b5e-1188-471d-b173-9c218eba76a6)

### Which customers would this be available to

Everyone - CE/Starter/Team/Enterprise

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
A couple of short coming I see here is:

* We want to export all 995 env vars except the 5 "XXX_PASSWORD" env vars - these should never be exposed to the file system or included in a download!
* We want to export all 1000 env vars but leave specific keys (like "XXX_PASSWORD") empty (so it can be filled in by the recipient instance before firing it up) 
* We want to import the snapshot and leave any existing ENV VARS in tact - like the pipeline does today. That permits us to prepare the new instances ahead of time and simply import the snapshot leaving the 5 "XXX_PASSWORD" fields I already setup on the new instance intact.

Given the option to simply exclude or include (keys with or without values) is not really helpful in the above situations.


I realised these may be follow up items but I wanted to explicitly call them out (slightly exaggerated) to put emphasis on the short fall I see.

**Comment by Steve-Mcl** [comment]
Mock up of download:

![image](https://github.com/user-attachments/assets/b79bafed-92a3-413f-9247-f6439b751802)


Mock up of upload:

![image](https://github.com/user-attachments/assets/be9dc588-a5f3-40eb-a47f-4188be0f5a45)


@joepavitt - ok to proceed?

**Comment by joepavitt** [comment]
Yes please

**Comment by joepavitt** [comment]
> I realised these may be follow up items but I wanted to explicitly call them out (slightly exaggerated) to put emphasis on the short fall I see.

Agreed, follow up item. Let's at least give them the option to have just the flows transferred over, env vars refinement can follow
