### ISSUE TITLE
Improve feedback in 'Instance Crashed' email

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#4653]
The email sent when an instance has crashed is extremely minimal and doesn't provide much help to the user as to what to do next, other than look at the logs.

<img width="634" alt="image" src="https://github.com/user-attachments/assets/ae01e0df-cd1f-4cba-a69e-a6b1a3ac684f">

It would be better to provide some more context to help the user decide what to do next.

The email is triggered by the launcher posting an audit-log entry following the abnormal exit of the NR process. If the launcher can provide some more information in that audit log entry we will be able to show that in the audit log as well as in the email.

Some initial thoughts/questions/things to investigate

1. Can the launcher tell the difference between 'killed due to memory' and 'uncaught exception' - the two most likely causes. If so, tailor the message accordingly.
2. Include a snippet of the logs preceding the exit. If there's an uncaught exception, we should be able to parse that out. It may be trickier to include the logs in the email and get the formatting right.
3. Depending on any insight we can infer from the logs, include recommended actions in the email.

The email should also include the team name to provide more context for what instance has crashed.
```[tasklist]
### Tasks
- [ ] https://github.com/FlowFuse/nr-launcher/issues/311
- [ ] https://github.com/FlowFuse/flowfuse/issues/4934
- [ ] https://github.com/FlowFuse/website/issues/2897
```

**Comment by Steve-Mcl** [comment]
In order to include logs in the email, the narrow HTML format would suit being adjusted somewhat.

For example this is what logs in the unmodified layout look like:

![Image](https://github.com/user-attachments/assets/17c536ed-4160-43cc-81dc-5d7296a2a674)


By increasing max-width from 600 to 1200, this looks better and makes better use of available space

![Image](https://github.com/user-attachments/assets/d163f76e-6028-42d3-8f52-6985dadba06a)


@cstns / @joepavitt - are we ok with adjusting the email layout to incorporate log table?

**Comment by cstns** [comment]
I don't see a problem with adjusting the width as long as it plays nicely with most email readers. I don't remember it being a topic of interest it was just that we didn't have a lot of content to display during the mvp and left it at that.

**Comment by joepavitt** [comment]
Can we put it in a `<details>` so that if people are viewing it on mobile it's not a massive scroll job?

**Comment by Steve-Mcl** [comment]
> Can we put it in a `<details>` so that if people are viewing it on mobile it's not a massive scroll job?

Great minds think alike - that was what I tried first. Unfortunately...

> While the `<details>` and `<summary>` elements are valid HTML5 and work in modern browsers, they have inconsistent support in email clients.
> 
> This means that while the HTML might be correctly interpreted in some email clients (like Apple Mail or Outlook for Mac), it's likely to fail in others (like Gmail, Outlook on Windows, or older email clients). In those cases, the content within the `<details>` tag might be displayed by default (ignoring the intended "hide/show" functionality), or it might not be displayed at all.
> 
> Therefore, it's generally not recommended to use `<details>` and `<summary>` in HTML emails if you need consistent rendering across different email clients.

NOTE: I do limit the log to 20 entries since typically, that is where the v8::xxx errors start apearing (it was originally 10 rows but I could not reliably determined the Out Of Memory error at 10 lines only.

**Comment by Steve-Mcl** [comment]
I can add you @joepavitt (or @cstns ) as an additional reviewer if desired - in case there is some formatting or other issue you wish to be improved?  (PR in comming)

**Comment by joepavitt** [comment]
This can now be closed, right?
