### ISSUE TITLE
Hierarchical Audit Logging

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4684]
### Description

When viewing the Audit Log view at the Team/Application levels, I would expect to see any logs related to elements contained _within_ that thing, i.e. in the Application's Audit Log, I'd expect to see all events linked to Instances & Devices within that Application.

Currently though we only see events/logs associated to the Application itself, not it's children.

This FR covers adding the hierarchical audit logging being available at the Application & Team levels. Implementation should be split into the following tasks:

```[tasklist]
### Tasks
- [ ] https://github.com/FlowFuse/flowfuse/issues/4746
- [ ] https://github.com/FlowFuse/flowfuse/issues/4750
- [ ] https://github.com/FlowFuse/website/issues/2759
```

### Which customers would this be available to

None

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
> i.e. in the Application's Audit Log, I'd expect to see all events linked to Instances & Devices within that Application.

I have the basic mechanics of this working as demonstrated below.

Questions:
1. Do we expect to see the "scope" as a column in the results or is it enough to be implicit at this stage?
2.  Should we default the scope to "team level only events" (as per current condition) and the user can then decide to select "All" or "Instance"
3. The title mentions "Hierarchical".  As development stands, the child results (Hierarchically speaking) are included when the "All" scope is selected. However, the view is NOT modified to show nested Hierarchical results.  To achieve nested views, the query would be much more complex.  
4. Again, title mentions "Hierarchical" so does that mean if the scope is set to "Application" that all application children (instances and devices) should be included.  Again, this makes the query much more complex,


![Image](https://github.com/user-attachments/assets/d712f24b-74e1-484a-8463-c5e9b116d917)

**Comment by joepavitt** [comment]
> Do we expect to see the "scope" as a column in the results or is it enough to be implicit at this stage?

Implicit

> Should we default the scope to "team level only events" (as per current condition) and the user can then decide to select "All" or "Instance"

No, the default should be "All", as that is what I believe the user has as an expectation when viewing this screen, and the feedback we've received.

> The title mentions "Hierarchical". As development stands, the child results (Hierarchically speaking) are included when the "All" scope is selected. However, the view is NOT modified to show nested Hierarchical results. To achieve nested views, the query would be much more complex.

Slightly mis-leading title I guess. Hierarchical just referred to all the child logs to be included, rather than presenting as a structural hierarchy

> Again, title mentions "Hierarchical" so does that mean if the scope is set to "Application" that all application children (instances and devices) should be included. Again, this makes the query much more complex,

I'm okay with it as you have it

**Comment by Steve-Mcl** [comment]
@joepavitt following our discussion around the inclusion of the "Include children" - I believe adding this to the Project Audit view is quite a simple matter.  

I can add that to the PR or we could add another task to the OP?

**Comment by joepavitt** [comment]
Another task please, iteration, iteration, iteration :)
