### ISSUE TITLE
Auto-detection of Schema

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4788]
We've proposed (in #3445) the idea of offering a Schema Builder, but as pointed out by customers we've discussed this with, this would be a significant undertaking to flesh out and define for full scale factory ecosystems, etc.

Alternatively, we could provide an "auto-detection" option, whereby, based on values we're seeing come into different topics, we could try to offer proposals for schemas, e.g. payloads that are `email`, `number`, `string`, `array`, or whichever definitions we decide upon.

Differentiation here is important for:

- FlowFuse Broker
- Bring Your Own Broker

We then have two levels of Schema:

- Topic Hierarchy
- Payload Structure

Will also pair with https://github.com/FlowFuse/flowfuse/issues/4908 whereby any schema we "store" will be structured as to work with Async API

```[tasklist]
### Tasks
- [ ] https://github.com/FlowFuse/flowfuse/issues/4963
- [ ] https://github.com/FlowFuse/flowfuse/issues/5036
```

```[tasklist]
### Topics
- [ ] https://github.com/FlowFuse/flowfuse/issues/4919
- [ ] https://github.com/FlowFuse/flowfuse/issues/5013
- [x] Monitor third-party brokerd to generate topic hierarchy schemas
```

```[tasklist]
### Payloads
- [ ] https://github.com/FlowFuse/mqtt-schema-agent/pull/3
- [ ] https://github.com/FlowFuse/flowfuse/issues/5032
- [ ] https://github.com/FlowFuse/flowfuse/issues/5125
```

### Available To

- Enterprise Tier Customers Only

**Comment by joepavitt** [comment]
@hardillb for the first part of this _"Monitor the latest message received on each topic"_ - what are are (technical) options here, other than subscribe to `/#`?

**Comment by hardillb** [comment]
None

And it's `#` NOT `/#` these are very different things

**Comment by joepavitt** [comment]
Okay, so `#` subscriptions it will need to be

**Comment by joepavitt** [comment]
#5125 is the last outstanding item here, core work has been delivered/

**Comment by joepavitt** [comment]
Calling this work closed out as major items have been delivered
