### ISSUE TITLE
New Team Level Views

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4820]
### Description

As part of the work with the [sidebar redesign](https://github.com/FlowFuse/flowfuse/pull/4745), we will introduce new team-level views for three of our offerings. This Epic is for tracking progress in implementing these views:

```[tasklist]
### Views
- [ ] https://github.com/FlowFuse/flowfuse/issues/4822
- [ ] https://github.com/FlowFuse/flowfuse/issues/4823
- [ ] https://github.com/FlowFuse/flowfuse/issues/4874
```

### Which customers would this be available to

Everyone - CE/Starter/Team/Enterprise

**Comment by joepavitt** [comment]
All children items are completed, can be closed
