### ISSUE TITLE
Restore platform wide link interaction

### ISSUE THREAD

**Issue by cstns** [FlowFuse/flowfuse#4836]
### Description

General initiative to improve ux with the platform by allowing users to interact with all links in a predictable manner with mouse + key combinations 

### Which customers would this be available to

Everyone - CE/Starter/Team/Enterprise

### Acceptance Criteria

- [ ] Links should be able to be interacted with via click + keyboard combo (ctrl/cmd+click)
- [ ] Links should be able to be interacted with via middle button click

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate
```[tasklist]
### Tasks
- [ ] https://github.com/FlowFuse/flowfuse/issues/4837
- [ ] https://github.com/FlowFuse/flowfuse/issues/4838
- [ ] https://github.com/FlowFuse/flowfuse/pull/4885
- [ ] https://github.com/FlowFuse/flowfuse/pull/4891
- [ ] https://github.com/FlowFuse/flowfuse/pull/4942
- [ ] https://github.com/FlowFuse/flowfuse/pull/4905
- [ ] Restore Link interactions in the PageHeader - Team Selector & Right menu dropdown
- [ ] Restore Link interactions on the remainder tabs of the applications page
- [ ] Restore Link interactions on the team instances page
- [ ] Restore Link interactions on the team devices page
- [ ] Restore Link interactions on the team broker page
- [ ] Restore Link interactions on the team library page
- [ ] Restore Link interactions on the team members [age
- [ ] Restore Link interactions on the team audit log page
- [ ] Restore Link interactions on the team setting page
- [ ] Restore Link interactions on the team billing page
- [ ] Restore Link interactions on the account settings section
- [ ] Restore Link interactions on the admin section
```

**Comment by cstns** [comment]
IMO this story should not have been assigned a milestone to begin with as it's a chore task to improve UX, not being mission critical it can be acted upon when we have time to spare

**Comment by joepavitt** [comment]
This has been achieved through the detailed PRs. Any issues found moving forward can have new issues raised
